import {withDatabase} from '@/db/database';
import {accountFromHeaders,privateHeaders,sameOrigin} from '@/lib/auth';
import {billingEnv,encryptConfig,getBillingConfig,insertIgnore,isAdmin,PROJECT_PRICE} from '@/lib/billing';
import {stripeClient} from '@/lib/stripe-payments';
export async function GET(req:Request){try{return await withDatabase(async db=>{const user=await accountFromHeaders(db,req.headers);if(!isAdmin(user))return Response.json({error:'Adminisztrátori jogosultság szükséges.'},{status:403,headers:privateHeaders});const {config,revision}=await getBillingConfig(db);const orders=await db.all('SELECT o.id, o.kind, o.amount, o.currency, o.mode, o.status, o.session_id, o.created_at, u.email FROM billing_orders o JOIN users u ON u.id = o.user_id ORDER BY o.created_at DESC LIMIT 50');return Response.json({enabled:config.enabled,mode:config.mode,price:PROJECT_PRICE,revision,encryptionReady:!!billingEnv().BILLING_ENCRYPTION_KEY,webhookUrl:(billingEnv().APP_ORIGIN||new URL(req.url).origin)+'/api/stripe/webhook',test:{secretKey:!!config.test.secretKey,webhookSecret:!!config.test.webhookSecret},live:{secretKey:!!config.live.secretKey,webhookSecret:!!config.live.webhookSecret},orders},{headers:privateHeaders})})}catch{return Response.json({error:'A fizetési beállítások nem tölthetők be.'},{status:503,headers:privateHeaders})}}
export async function POST(req:Request){try{const raw=await req.text();if(!sameOrigin(req))return Response.json({error:'Érvénytelen kérés.'},{status:403,headers:privateHeaders});if(raw.length>8000)throw Error('Túl nagy kérés.');const data=JSON.parse(raw);return await withDatabase(async db=>{const user=await accountFromHeaders(db,req.headers);if(!isAdmin(user))return Response.json({error:'Adminisztrátori jogosultság szükséges.'},{status:403,headers:privateHeaders});const {config,revision}=await getBillingConfig(db);if(data.action==='test'){if(!['test','live'].includes(data.mode))throw Error('Érvénytelen üzemmód.');const mode=data.mode as 'test'|'live';if(!config[mode].secretKey)throw Error('Előbb mentsd el a Stripe-kulcsot.');await stripeClient(config[mode].secretKey).balance.retrieve();return Response.json({ok:true,message:'A Stripe API-kapcsolat működik. A webhookot külön tesztfizetéssel ellenőrizd.'},{headers:privateHeaders})}
 if(data.action!=='save'||data.revision!==revision)return Response.json({error:'A beállítások megváltoztak. Töltsd újra a panelt.'},{status:409,headers:privateHeaders});if(typeof data.enabled!=='boolean'||!['test','live'].includes(data.mode))throw Error('Érvénytelen beállítás.');config.enabled=data.enabled;config.mode=data.mode;
 for(const mode of ['test','live'] as const){for(const field of ['secretKey','webhookSecret'] as const){const value=data[mode]?.[field];if(value===undefined||value==='')continue;if(typeof value!=='string'||value.length>500)throw Error('Érvénytelen Stripe-kulcs.');const valid=field==='secretKey'?new RegExp('^(sk|rk)_'+mode+'_[a-zA-Z0-9]+$').test(value):/^whsec_[a-zA-Z0-9]+$/.test(value);if(!valid)throw Error('A kulcs formátuma vagy teszt/éles típusa hibás.');config[mode][field]=value}}
 if(config.enabled&&(!config[config.mode].secretKey||!config[config.mode].webhookSecret))throw Error('Az engedélyezéshez Stripe API- és webhookkulcs is szükséges.');
 const encrypted=await encryptConfig(config),now=new Date().toISOString();const changed=revision===0?await db.run(insertIgnore(db,'INSERT INTO billing_settings (id,data,revision,updated_at) VALUES (?,?,?,?)'),['stripe',encrypted,1,now]):await db.run('UPDATE billing_settings SET data = ?, revision = revision + 1, updated_at = ? WHERE id = ? AND revision = ?',[encrypted,now,'stripe',revision]);if(!changed)return Response.json({error:'Másik ablakban módosult. Frissítsd a panelt.'},{status:409,headers:privateHeaders});return Response.json({ok:true},{headers:privateHeaders})})}catch(e){return Response.json({error:e instanceof Error&&!(e as {type?:string}).type?e.message:'A Stripe-kapcsolat sikertelen. Ellenőrizd a kulcsot és a jogosultságait.'},{status:400,headers:privateHeaders})}}
