import assert from 'node:assert/strict';
import {seed,validatePlan} from '../lib/plan';
import {newOpening,allOpenings,wallHosts,solidWallSegments,nearestOpeningHost,validateArchitecture} from '../lib/architecture';
import {translateFloor} from '../lib/geometry';
import {translateFloorSelection} from '../lib/floor-selection';
import {copyStructure} from '../lib/structure-copy';
import {wallSnap} from '../lib/wall-snap';
const p=validatePlan(structuredClone(seed)),f=p.buildings[0].floors[0];
assert.equal(wallHosts(f)[0].thickness,17.5,'legacy wall width is preserved');
const door={...newOpening('door',1,.3),id:'door'},window={...newOpening('window',0,.7),id:'window'};
f.rooms[0].openings=[door,window];f.rooms[0].thickness=30;validatePlan(p);
const host=wallHosts(f).find(h=>h.id==='living')!,other=wallHosts(f).find(h=>h.id==='bed')!;
assert.equal(host.thickness,30);
const g=allOpenings(f).find(v=>v.opening.id==='door')!.geometry;
assert.deepEqual(g.center,{x:500,y:260});assert.deepEqual(g.start,{x:500,y:242});assert.deepEqual(g.end,{x:500,y:278});
assert.ok(!solidWallSegments(f,other).some(([a,b])=>a.x===500&&b.x===500&&Math.min(a.y,b.y)<260&&Math.max(a.y,b.y)>260),'shared room wall has matching gap');
assert.equal(wallSnap({x:500,y:260},f,0,10),null,'no snap inside a shared opening');
const hit=nearestOpeningHost(f,{x:501,y:300},90)!;assert.equal(hit.host.id,'living');assert.equal(hit.edge,1);
assert.equal(nearestOpeningHost(f,{x:50,y:50},90),null);
const snap=JSON.stringify(f),moved=translateFloor(f,{type:'rooms',id:'living',dx:40,dy:80});
const gm=allOpenings(moved).find(o=>o.opening.id==='door')!.geometry;assert.deepEqual(gm.center,{x:540,y:340});assert.equal(JSON.stringify(f),snap);
const group=translateFloorSelection(f,[{type:'rooms',id:'living'},{type:'rooms',id:'bed'}],40,40);assert.deepEqual(allOpenings(group)[0].geometry.center,{x:540,y:300});validateArchitecture(group);
const bad=structuredClone(p);bad.buildings[0].floors[0].rooms[0].openings![0].width=4000;assert.throws(()=>validatePlan(bad));
const short=structuredClone(f);short.rooms[0].h=20;assert.throws(()=>validateArchitecture(short),/nem fér/);
const duplicate=structuredClone(p);duplicate.buildings[0].floors[0].rooms[0].openings![1].id='door';assert.throws(()=>validatePlan(duplicate),/azonosító/);
const overlap=structuredClone(f);overlap.rooms[1].openings=[{...newOpening('window',3,100/220),width:90}];assert.throws(()=>validateArchitecture(overlap),/átfedi/);
const options={buildingId:'house',floorId:'ground',name:'Másolat',elevation:6,dx:680,dy:0,contents:true,keepCircuits:false,panels:false,background:false};
const copy=copyStructure(p,options).plan.buildings[0].floors.at(-1)!;assert.equal(allOpenings(copy).length,2);assert.ok(allOpenings(copy).every(o=>!['door','window'].includes(o.opening.id)));assert.deepEqual(allOpenings(copy)[0].geometry.center,g.center);assert.equal(copy.rooms[0].thickness,30);
const roomCopy=copyStructure(p,{...options,roomId:'living',contents:false}).plan;validatePlan(roomCopy);assert.equal(roomCopy.buildings[0].floors[0].rooms.at(-1)!.openings!.length,2,'structural openings copy with the room even without electrical contents');
f.walls=[{id:'diagonal',a:{x:100,y:100},b:{x:200,y:200},thickness:10,openings:[newOpening('door')]}];validatePlan(p);
const diagonal=allOpenings(f).find(o=>o.host.id==='diagonal')!;assert.ok(Math.abs(diagonal.geometry.center.x-150)<1e-10);
const bounded=translateFloor(f,{type:'walls',id:'diagonal',dx:-500,dy:-500});assert.deepEqual(bounded.walls[0].a,{x:0,y:0});assert.deepEqual(bounded.walls[0].b,{x:100,y:100});validateArchitecture(bounded);
const copyWalls=copyStructure(p,options).plan.buildings[0].floors.at(-1)!;assert.notEqual(copyWalls.walls[0].openings![0].id,f.walls[0].openings![0].id);
assert.equal(allOpenings(validatePlan(JSON.parse(JSON.stringify(p))).buildings[0].floors[0]).length,3);
console.log('PASS: legacy schema, shared wall gaps, snapping, host and group movement, diagonal/bounded walls, opening validation, unique copied IDs and JSON round trip.');
