// Run only against a local ShockCraft preview with the D1 migrations applied.
import assert from 'node:assert/strict';
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:5180';
if(!['127.0.0.1','localhost'].includes(new URL(base).hostname))throw Error('Use a loopback test server.');
const id=Date.now()+'-'+Math.random().toString(36).slice(2),password='Test passphrase '+id;
const plan={version:1,name:'Auth isolation test',plot:{name:'Telek',w:40,h:30,nodes:[],routes:[]},buildings:[{id:'house',name:'Ház',x:2,y:2,w:10,h:10,floors:[{id:'floor',name:'Földszint',elevation:0,rooms:[],walls:[],devices:[],routes:[]}]}],circuits:[],modules:[]};
async function call(path,method='GET',body,cookie='',extra={}){const r=await fetch(base+path,{method,headers:{Origin:base,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{}),...extra},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});return{status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0],headers:r.headers}}
assert.equal((await call('/api/plan')).status,401);
assert.equal((await call('/api/plan','GET',undefined,'',{'oai-authenticated-user-id':'forged','oai-authenticated-user-email':'forged@example.test'})).status,401);
assert.equal((await call('/api/auth/register','POST',{name:'Test',email:'weak-'+id+'@example.test',password:'short'})).status,400);
assert.equal((await call('/api/auth/register','POST',{name:'Test',email:'long-'+id+'@example.test',password:'á'.repeat(40)})).status,400);
assert.equal((await call('/api/auth/login','POST',{email:'unknown-'+id+'@example.test',password})).status,401);
const a=await call('/api/auth/register','POST',{name:"Teszt O'Name",email:'A-'+id+'@example.test',password});assert.equal(a.status,200);assert.ok(a.cookie);assert.match(a.headers.get('set-cookie'),/HttpOnly/);assert.match(a.headers.get('set-cookie'),/SameSite=Lax/);assert.equal(a.data.account.email,'a-'+id+'@example.test');assert.ok(!JSON.stringify(a.data).includes('password'));
assert.equal((await call('/api/auth/register','POST',{name:'Duplicate',email:'a-'+id+'@example.test',password})).status,409);
const b=await call('/api/auth/register','POST',{name:'Másik felhasználó',email:'b-'+id+'@example.test',password});assert.equal(b.status,200);
const body={plan,revision:0,userId:a.data.account.userId};assert.equal((await call('/api/plan','PUT',body,a.cookie)).status,200);assert.equal((await call('/api/plan','GET',undefined,a.cookie)).data.plan.name,plan.name);
assert.equal((await call('/api/plan','GET',undefined,b.cookie)).data.plan,null);assert.equal((await call('/api/plan','PUT',body,b.cookie)).status,409);
assert.equal((await call('/api/plan','PUT',body,a.cookie)).status,409);
const projectId=crypto.randomUUID(),secondId=crypto.randomUUID();
assert.equal((await call('/api/plan?list=1')).status,401);
assert.equal((await call('/api/plan','PUT',{...body,projectId,plan:{...plan,name:'Első külön projekt'}},a.cookie)).status,200);
assert.equal((await call('/api/plan','PUT',{...body,projectId:secondId,plan:{...plan,name:'Második külön projekt',buildings:[]}},a.cookie)).status,200);
const list=(await call('/api/plan?list=1','GET',undefined,a.cookie)).data.projects;
assert.equal(list.length,3);assert.ok(list.some(p=>p.id==='default'));assert.ok(list.some(p=>p.id===projectId&&p.name==='Első külön projekt'));
assert.equal((await call('/api/plan?list=1','GET',undefined,b.cookie)).data.projects.length,0);
assert.equal((await call('/api/plan?projectId='+projectId,'GET',undefined,b.cookie)).status,404);
assert.equal((await call('/api/plan?projectId='+projectId,'GET',undefined,a.cookie)).data.plan.name,'Első külön projekt');
assert.equal((await call('/api/plan?projectId='+secondId,'GET',undefined,a.cookie)).data.plan.buildings.length,0);
assert.equal((await call('/api/plan','PUT',{...body,projectId},a.cookie)).status,409);
assert.equal((await call('/api/plan','PUT',{...body,projectId,revision:1,plan:{...plan,name:'Átnevezve'}},a.cookie)).status,200);
assert.equal((await call('/api/plan?projectId='+projectId,'GET',undefined,a.cookie)).data.plan.name,'Átnevezve');
assert.equal((await call('/api/plan','GET',undefined,a.cookie)).data.plan.name,plan.name);
assert.equal((await call('/api/plan?projectId=account:other','GET',undefined,a.cookie)).status,400);
assert.equal((await call('/api/plan','PUT',{...body,projectId:'%'},a.cookie)).status,400);
assert.equal((await call('/api/plan','PUT',{...body,revision:1},a.cookie,{Origin:'https://elsewhere.test'})).status,403);
assert.equal((await call('/api/auth/logout','POST',undefined,a.cookie,{Origin:'https://elsewhere.test'})).status,403);
assert.equal((await call('/api/auth/logout','POST',undefined,a.cookie)).status,200);assert.equal((await call('/api/plan','GET',undefined,a.cookie)).status,401);
assert.equal((await call('/api/auth/login','POST',{email:a.data.account.email,password:'wrong password 123'})).status,401);
const signed=await call('/api/auth/login','POST',{email:a.data.account.email,password});assert.equal(signed.status,200);assert.notEqual(signed.cookie,a.cookie);assert.equal((await call('/api/plan','GET',undefined,signed.cookie)).data.plan.name,plan.name);
const rotated=await call('/api/auth/login','POST',{email:a.data.account.email,password},signed.cookie);assert.equal(rotated.status,200);assert.equal((await call('/api/plan','GET',undefined,signed.cookie)).status,401);
for(let i=0;i<12;i++)assert.equal((await call('/api/auth/login','POST',{email:'limited-'+id+'@example.test',password:'too-short'})).status,400);
assert.equal((await call('/api/auth/login','POST',{email:'limited-'+id+'@example.test',password:'too-short'})).status,429);
console.log('PASS: registration, validation, duplicate email, cookies, login/logout/revocation, session rotation, persistence, account isolation, spoofed identity rejection, CSRF, stale revision and throttling.');
