import assert from 'node:assert/strict';
import {backgroundSchema,calibratedSize,jpegDimensions} from '../lib/background';
import {seed,validatePlan} from '../lib/plan';
const size=calibratedSize({x:.1,y:.2},{x:.6,y:.2},5,.75);
assert.deepEqual(size,{w:400,h:300});
assert.deepEqual(calibratedSize({x:.1,y:.1},{x:.1,y:.6},3,.6),{w:400,h:240});
assert.throws(()=>calibratedSize({x:0,y:0},{x:0,y:0},5,1));
assert.throws(()=>calibratedSize({x:0,y:0},{x:.1,y:0},100,1));
assert.throws(()=>calibratedSize({x:0,y:0},{x:.5,y:0},NaN,1));
const plan=validatePlan(seed),before=structuredClone(plan.buildings[0].floors[0]);
plan.buildings[0].floors[0].background={assetId:crypto.randomUUID(),name:'Alaprajz.jpg',x:20,y:40,...size,opacity:.55,visible:true,calibrated:true};
const roundtrip=validatePlan(JSON.parse(JSON.stringify(plan)));
assert.deepEqual(roundtrip,plan);
assert.deepEqual(roundtrip.buildings[0].floors[0].devices,before.devices);
assert.deepEqual(roundtrip.buildings[0].floors[0].routes,before.routes);
assert.equal(roundtrip.buildings[0].floors[1].background,undefined);
assert.equal(validatePlan(seed).buildings[0].floors[0].background,undefined);
assert.throws(()=>backgroundSchema.parse({...plan.buildings[0].floors[0].background,x:1900}));
assert.throws(()=>backgroundSchema.parse({...plan.buildings[0].floors[0].background,assetId:'../../other-user'}));
assert.throws(()=>jpegDimensions(new TextEncoder().encode('<svg onload=evil>')));
assert.deepEqual(jpegDimensions(Uint8Array.from([255,216,255,192,0,11,8,0,100,0,200,1,1,17,0,255,217])),{w:200,h:100});
assert.throws(()=>jpegDimensions(Uint8Array.from([255,216,255,192,0,11,8,255,255,0,200,1,1,17,0,255,217])));
console.log('Background calibration, persistence, isolation and image validation passed.');
