import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import type {Database} from '../db/database';
import {claimProject,billingStatus,encryptConfig,getBillingConfig,isAdmin} from '../lib/billing';
import {checkout,fulfillCheckout,stripeClient} from '../lib/stripe-payments';
import Stripe from 'stripe';
const sql=new DatabaseSync(':memory:');sql.exec('CREATE TABLE plans(id TEXT PRIMARY KEY,data TEXT,revision INTEGER,updated_at TEXT)');
sql.exec(readFileSync('drizzle/0002_aspiring_husk.sql','utf8').replaceAll('--> statement-breakpoint',''));
const db:Database={kind:'d1',async first<T>(s:string,p:(string|number|null)[]=[]){return (sql.prepare(s).get(...p)||null) as T|null},async all<T>(s:string,p:(string|number|null)[]=[]){return sql.prepare(s).all(...p) as T[]},async run(s,p=[]){return Number(sql.prepare(s).run(...p).changes)}};
const user={userId:'user-a',email:'a@example.test',displayName:'A'},other={...user,userId:'user-b'},admin={...user,userId:'test-admin'};
assert.equal(isAdmin(user),false);assert.equal(isAdmin(admin),true);
const races=await Promise.all([claimProject(db,user,'one'),claimProject(db,user,'two')]);assert.equal(races.filter(Boolean).length,1,'one free project under concurrent claims');
const accepted=races[0]?'one':'two';assert.equal(await claimProject(db,user,accepted),true,'retry same project does not consume another grant');assert.equal(await claimProject(db,user,'three'),false);
sql.prepare('INSERT INTO plans VALUES (?,?,?,?)').run('account:legacy','{}',1,'2020');assert.equal(await claimProject(db,{...user,userId:'legacy'},'new'),false,'existing projects consume the free entitlement');
const config={enabled:true,mode:'test' as const,test:{secretKey:'sk_test_notreal',webhookSecret:'whsec_testsecret'},live:{secretKey:'sk_live_notreal',webhookSecret:'whsec_livesecret'}};
const ciphertext=await encryptConfig(config);assert.ok(!ciphertext.includes('sk_test'));await db.run('INSERT INTO billing_settings VALUES (?,?,?,?)',['stripe',ciphertext,1,'2026']);assert.deepEqual((await getBillingConfig(db)).config,config);
assert.equal((await billingStatus(db,user)).ready,false,'ordinary users cannot buy in test mode');
await assert.rejects(()=>checkout(db,user,crypto.randomUUID()),/nincs engedélyezve/);
const orderId=crypto.randomUUID();let creates=0;const originalFetch=globalThis.fetch;
globalThis.fetch=async (input,init)=>{const url=String(input);assert.ok(url.startsWith('https://api.stripe.com/'));const body=new URLSearchParams(String(init?.body));assert.equal(body.get('line_items[0][price_data][unit_amount]'),'349000');assert.equal(body.get('mode'),'payment');assert.equal(body.get('client_reference_id'),'test-admin');assert.equal(body.get('metadata[order_id]'),orderId);creates++;return new Response(JSON.stringify({id:'cs_test_checkout123456',object:'checkout.session',url:'https://checkout.stripe.com/c/pay/cs_test_checkout123456'}),{status:200,headers:{'content-type':'application/json'}})};
assert.match(await checkout(db,admin,orderId),/^https:\/\/checkout.stripe.com/);assert.equal(creates,1);globalThis.fetch=originalFetch;
const session={id:'cs_test_checkout123456',mode:'payment',payment_status:'paid',client_reference_id:admin.userId,metadata:{order_id:orderId,user_id:admin.userId},amount_total:349000,currency:'huf',livemode:false} as unknown as Stripe.Checkout.Session;
await Promise.all([fulfillCheckout(db,session,'test'),fulfillCheckout(db,session,'test')]);assert.equal((await db.all('SELECT id FROM billing_grants WHERE id = ?',['stripe:'+orderId])).length,1,'duplicate webhook grants once');
assert.equal(await fulfillCheckout(db,{...session,payment_status:'unpaid'},'test'),false);
await assert.rejects(()=>fulfillCheckout(db,{...session,amount_total:3490},'test'),/eltérnek/);await assert.rejects(()=>fulfillCheckout(db,{...session,client_reference_id:other.userId},'test'),/eltérnek/);await assert.rejects(()=>fulfillCheckout(db,session,'live'),/eltérnek/);
const payload=JSON.stringify({id:'evt_test',type:'checkout.session.completed',livemode:false,data:{object:session}}),stripe=stripeClient(config.test.secretKey);const header=stripe.webhooks.generateTestHeaderString({payload,secret:config.test.webhookSecret});assert.equal((await stripe.webhooks.constructEventAsync(payload,header,config.test.webhookSecret,300,Stripe.createSubtleCryptoProvider())).id,'evt_test');await assert.rejects(()=>stripe.webhooks.constructEventAsync(payload+' ',header,config.test.webhookSecret,300,Stripe.createSubtleCryptoProvider()));
// A test credit cannot unlock an ordinary user's live project.
await db.run('INSERT INTO billing_grants VALUES (?,?,?,?,?)',['test-only',user.userId,null,'test',Date.now()]);assert.equal(await claimProject(db,user,'four'),false);
await db.run('INSERT INTO billing_grants VALUES (?,?,?,?,?)',['live-paid',user.userId,null,'live',Date.now()]);assert.equal(await claimProject(db,user,'four'),true);assert.equal(await claimProject(db,user,'five'),false);
for(let i=0;i<9;i++)await db.run('INSERT INTO billing_orders VALUES (?,?,?,?,?,?,?,?,?)',[crypto.randomUUID(),admin.userId,349000,'huf','test','pending',null,Date.now(),Date.now()]);
await assert.rejects(()=>checkout(db,admin,crypto.randomUUID()),/15 perc/);
console.log('PASS: atomic free/paid entitlements, legacy projects, encrypted keys, admin-only test mode, Stripe amount/metadata, duplicate fulfillment, amount/owner/mode checks and signed raw webhook validation.');
