import assert from 'node:assert/strict';
import {seed,validatePlan} from '../lib/plan';
import {boardSize,boardSizeIssue,findModulePlace} from '../lib/board-size';
import {cabinetLayout,connectTerminals} from '../lib/cabinet';
import {toggleDeviceCircuit} from '../lib/circuit-assignment';
import {createPlanPdf} from '../lib/pdf-export';
import {readFileSync} from 'node:fs';
const p=validatePlan(structuredClone(seed));
assert.deepEqual(boardSize(p.buildings[0]),{rows:4,modulesPerRow:18},'legacy projects keep their default board');
assert.ok(boardSizeIssue(p,'house',{rows:1,modulesPerRow:6}));
assert.equal(boardSizeIssue(p,'house',{rows:1,modulesPerRow:12}),null);
p.buildings[0].board={rows:6,modulesPerRow:24};
assert.deepEqual(findModulePlace(p,'house',4),{row:0,slot:11});
p.modules.push({id:'last',name:'Last slot',building:'house',type:'MCB',width:1,row:5,slot:23,circuit:''});
validatePlan(p);
const layout=cabinetLayout(p,'house');assert.equal(layout.rows.length,6);assert.equal(layout.size.modulesPerRow,24);assert.equal(layout.railWidth,1920);assert.equal(layout.devices.at(-1)?.module.id,'last');
assert.equal(cabinetLayout(p,'garage').rows.length,4,'settings isolated per building');
assert.ok(boardSizeIssue(p,'house',{rows:5,modulesPerRow:24}));assert.ok(boardSizeIssue(p,'house',{rows:6,modulesPerRow:23}));
for(const size of [{rows:0,modulesPerRow:18},{rows:13,modulesPerRow:18},{rows:4,modulesPerRow:37},{rows:1.5,modulesPerRow:18}])assert.ok(boardSizeIssue(p,'house',size));
const restored=validatePlan(JSON.parse(JSON.stringify(p)));assert.deepEqual(restored.buildings[0].board,p.buildings[0].board);
const bad=structuredClone(p);bad.buildings[0].board={rows:1,modulesPerRow:12};assert.throws(()=>validatePlan(bad),/modulhely/,'API/import validation rejects shrinking beyond devices');
const full=structuredClone(seed);full.buildings[0].board={rows:1,modulesPerRow:11};assert.equal(findModulePlace(full,'house',1),null);
const connected=connectTerminals(p,{kind:'module',id:'m0',port:'L1-out'},{kind:'module',id:'m1',port:'L1-in'},'test-wire');
const wires=JSON.stringify(connected.boardWires),routes=JSON.stringify(connected.buildings[0].floors[0].routes);
assert.equal(toggleDeviceCircuit(connected,'house','ground','d1','c2'),'c2');assert.equal(toggleDeviceCircuit(connected,'house','ground','d1','c2'),'');
assert.equal(toggleDeviceCircuit(connected,'house','ground','d1','c1'),'c1');
assert.equal(JSON.stringify(connected.boardWires),wires);assert.equal(JSON.stringify(connected.buildings[0].floors[0].routes),routes,'assignments do not invent or change route connectivity');
assert.throws(()=>toggleDeviceCircuit(connected,'garage','garagefloor','d1','c1'));assert.throws(()=>toggleDeviceCircuit(connected,'house','ground','d1','absent'));
validatePlan(connected);
const font=readFileSync('public/fonts/NotoSans-Regular.ttf').toString('base64');
const pdf=createPlanPdf(p,{scope:'board',paper:'a4',buildingId:'house',floorId:'ground'},font);assert.ok(pdf.getNumberOfPages()>=5,'six rows paginate plus registers');
console.log('PASS: legacy defaults, per-building size, bounds/shrink rejection, module placement, saved settings, click assign/reassign/remove, unchanged wiring and paginated PDF.');
