import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {seed,validatePlan,uid} from '../lib/plan';
import {moduleTypes,moduleWidths,circuitPorts,modulePorts,connectBoard,removeBoardLinks,pruneBoardLinks} from '../lib/board';
import {removeStructure} from '../lib/projects';
import {createPlanPdf} from '../lib/pdf-export';
const p=validatePlan(seed);
assert.deepEqual(p.boardWires,[]);
let row=1,slot=0;
for(const type of moduleTypes.filter(t=>!['MCB','RCD','RCBO','SPD','MAIN'].includes(t))){const width=moduleWidths[type];if(slot+width>18){row++;slot=0}p.modules.push({id:uid(),name:type+' próba',building:'house',type,width,row,slot,circuit:''});slot+=width}
const wire=(from:any,to:any)=>({id:uid(),name:'Próba vezeték',building:'house',from,to});
const from={kind:'circuit' as const,id:'c1',port:'L'},to={kind:'module' as const,id:'m2',port:'L-out'};
connectBoard(p,wire(from,to));
assert.equal(p.modules.find(m=>m.id==='m2')?.circuit,'c1');
assert.throws(()=>connectBoard(structuredClone(p),wire(from,to)),/már szerepel|már be van kötve/);
assert.throws(()=>connectBoard(structuredClone(p),wire({kind:'circuit',id:'c2',port:'L'},to)),/másik áramkör/);
const pe=p.modules.find(m=>m.type==='PE')!,n=p.modules.find(m=>m.type==='NEUTRAL')!;
connectBoard(p,wire({kind:'circuit',id:'c1',port:'PE'},{kind:'module',id:pe.id,port:'PE1'}));
connectBoard(p,wire({kind:'circuit',id:'c1',port:'N'},{kind:'module',id:n.id,port:'N1'}));
assert.throws(()=>connectBoard(structuredClone(p),wire({kind:'circuit',id:'c2',port:'L'},{kind:'module',id:n.id,port:'N2'})),/Eltérő/);
assert.throws(()=>connectBoard(structuredClone(p),wire({kind:'module',id:n.id,port:'N2'},{kind:'module',id:n.id,port:'N3'})),/különböző/);
const other=structuredClone(p);other.modules.find(m=>m.id===n.id)!.building='garage';assert.throws(()=>validatePlan(other),/másik épület/);
p.circuits[0].conductorNames={L:'W1 – nappali fázis'};
assert.equal(circuitPorts(p.circuits[0])[0].label,'W1 – nappali fázis');
assert.deepEqual(validatePlan(JSON.parse(JSON.stringify(p))),p);
const deleted=structuredClone(p);removeBoardLinks(deleted,'module','m2');deleted.modules=deleted.modules.filter(m=>m.id!=='m2');validatePlan(deleted);assert.equal(deleted.boardWires.length,2);
removeStructure(deleted,'house');assert.equal(deleted.boardWires.length,0);validatePlan(deleted);
const phase=structuredClone(p);phase.circuits[0].phase='3P';pruneBoardLinks(phase);validatePlan(phase);assert.equal(circuitPorts(phase.circuits[0]).length,5);assert.equal(modulePorts(phase.modules.find(m=>m.id==='m2')!,phase).length,6);assert.equal(phase.boardWires.length,2);
connectBoard(phase,wire({kind:'circuit',id:'c1',port:'L2'},{kind:'module',id:'m2',port:'L2-out'}));validatePlan(phase);
const changed=structuredClone(p);changed.modules.find(m=>m.id==='m2')!.circuit='c2';pruneBoardLinks(changed);validatePlan(changed);assert.equal(changed.boardWires.length,2);
const branch=p.modules.find(m=>m.type==='DISTRIBUTION')!;
connectBoard(p,wire({kind:'module',id:'m0',port:'L1-out'},{kind:'module',id:branch.id,port:'L1-1'}));
connectBoard(p,wire({kind:'module',id:branch.id,port:'L1-2'},{kind:'module',id:'m2',port:'L-in'}));
validatePlan(p);
writeFileSync('.sites-runtime/board-fixture.json',JSON.stringify(p));
const font=readFileSync('public/fonts/NotoSans-Regular.ttf').toString('base64');
const pdf=createPlanPdf(p,{scope:'board',paper:'a4',buildingId:'house',floorId:'ground'},font);
writeFileSync('.sites-runtime/board-test.pdf',Buffer.from(pdf.output('arraybuffer')));
assert.ok(pdf.getNumberOfPages()>=5);
console.log('Board wiring: legacy import, all device types, connection validation, 3P, cleanup, round-trip and PDF passed.');
