import assert from 'node:assert/strict';
import {copyDevice} from '../lib/device-copy';
import {seed,validatePlan,newFloor,type Device} from '../lib/plan';
const plan=validatePlan(seed),floor=plan.buildings[0].floors[0],before=JSON.stringify(plan);
const clone=copyDevice(floor,'d1'),source=floor.devices.find(d=>d.id==='d1')!;
assert.notEqual(clone.id,source.id);assert.equal(clone.name,'D-04');
for(const key of ['kind','height','angle','circuit'] as const)assert.equal(clone[key],source[key]);
assert.equal(clone.x,source.x);assert.equal(clone.y,source.y+40);assert.equal(JSON.stringify(plan),before);
floor.devices.push(clone);assert.equal(copyDevice(floor,clone.id).name,'D-05');assert.doesNotThrow(()=>validatePlan(plan));
assert.deepEqual(validatePlan(JSON.parse(JSON.stringify(plan))).buildings[0].floors[0].devices.at(-1),clone);
const panel=copyDevice(floor,'p1');floor.devices.push(panel);assert.equal(panel.kind,'panel');assert.deepEqual(plan.plot,JSON.parse(before).plot);assert.deepEqual(floor.routes,JSON.parse(before).buildings[0].floors[0].routes);
const f=newFloor('T',0),d:Device={id:'lamp',kind:'light',name:'Lámpa',x:2000,y:2000,height:260,angle:37,circuit:''};f.devices=[d];
const edge=copyDevice(f,d.id);assert.equal(edge.x,1960);assert.equal(edge.y,2000);assert.equal(edge.angle,37);assert.equal(edge.name,'Lámpa – másolat');
f.devices.push(edge);assert.equal(copyDevice(f,edge.id).name,'Lámpa – másolat 2');
f.devices=[{...d,x:100,y:100,name:'X'.repeat(120)}];assert.ok(copyDevice(f,d.id).name.length<=120);
f.devices=[{...d,x:100,y:100},{...d,id:'occupied',x:140,y:100}];
const free=copyDevice(f,d.id);assert.equal(free.x,100);assert.equal(free.y,140);
assert.throws(()=>copyDevice(f,'missing'),/nem található/);
f.devices=Array.from({length:2000},(_,i)=>({...d,id:String(i)}));assert.throws(()=>copyDevice(f,'0'),/2000/);
console.log('PASS: unique IDs/names, preserved circuit/height/angle/type, wall placement, occupied/boundary positions, immutable originals/routes/plot, JSON roundtrip and capacity guard.');
