import assert from 'node:assert/strict';
import {seed,validatePlan,type Floor} from '../lib/plan';
import {floorPoints,floorLength} from '../lib/geometry';
import {selectInBox,selectionBounds,selectionDelta,translateFloorSelection,uniqueSelection,type FloorSelection} from '../lib/floor-selection';
const f=validatePlan(structuredClone(seed)).buildings[0].floors[0];
f.walls=[{id:'wall',a:{x:100,y:100},b:{x:200,y:100}}];
f.dimensions=[{id:'dim',name:'Mérés',a:{x:100,y:100},b:{x:200,y:100},offset:40,mode:'aligned'}];
const snapshot=JSON.stringify(f), device=(id:string):FloorSelection=>({type:'devices',id}),route=(id:string):FloorSelection=>({type:'routes',id});
const group=[device('p1'),device('d1'),route('r1')];
const moved=translateFloorSelection(f,group,40,80);
assert.deepEqual(floorPoints(moved.routes[0],moved),floorPoints(f.routes[0],f).map(p=>({x:p.x+40,y:p.y+80})),'selected route and both endpoints translate exactly once');
assert.equal(floorLength(moved.routes[0],moved).total,floorLength(f.routes[0],f).total,'complete circuit run retains its length');
assert.equal(moved.devices.find(d=>d.id==='d2')!.x,f.devices.find(d=>d.id==='d2')!.x,'unselected device stays put');
assert.deepEqual(moved.routes[1],f.routes[1],'unrelated route stays unchanged');
assert.equal(moved.devices[0].circuit,f.devices[0].circuit);assert.equal(moved.devices[0].height,f.devices[0].height);assert.equal(moved.devices[0].angle,f.devices[0].angle);
const endsOnly=translateFloorSelection(f,[device('p1'),device('d1')],20,40);
assert.deepEqual(endsOnly.routes[0].points,f.routes[0].points,'unselected route bends stay put');
assert.deepEqual(floorPoints(endsOnly.routes[0],endsOnly)[0],{x:520,y:540});
const oneEnd=translateFloorSelection(f,[device('d1'),route('r1')],40,40),onePoints=floorPoints(oneEnd.routes[0],oneEnd);
assert.deepEqual(onePoints[0],{x:500,y:500},'unselected anchored endpoint is fixed');
assert.deepEqual(onePoints.at(-1),{x:220,y:300});assert.deepEqual(onePoints[1],{x:540,y:180});
const direct:Floor=structuredClone(f);direct.routes[0].points=[{x:500,y:500},{x:180,y:260}];
const shiftedDirect=translateFloorSelection(direct,[route('r1'),device('d2')],40,40);
assert.equal(shiftedDirect.routes[0].points.length,4,'direct anchored route gains movable bends');
assert.deepEqual(floorPoints(shiftedDirect.routes[0],shiftedDirect)[0],{x:500,y:500});assert.deepEqual(floorPoints(shiftedDirect.routes[0],shiftedDirect).at(-1),{x:180,y:260});
const free=structuredClone(f);free.routes[0].startId='';free.routes[0].endId='';
assert.deepEqual(translateFloorSelection(free,[route('r1'),device('d2')],40,40).routes[0].points,free.routes[0].points.map(p=>({x:p.x+40,y:p.y+40})));
const all:FloorSelection[]=[{type:'rooms',id:'living'},{type:'walls',id:'wall'},{type:'dimensions',id:'dim'},...group];
const shifted=translateFloorSelection(f,all,-100,-100);
assert.deepEqual(shifted.walls[0].a,{x:0,y:0});assert.deepEqual(shifted.walls[0].b,{x:100,y:0});
assert.deepEqual(shifted.dimensions![0].a,{x:0,y:0});assert.equal(shifted.dimensions![0].offset,40);assert.equal(shifted.rooms[0].x,80);assert.equal(shifted.rooms[0].w,320);
assert.equal(shifted.devices.find(d=>d.id==='l1')!.x,340,'room contents are not implicitly selected');
assert.deepEqual(selectionDelta(f,all,-9000,-9000),{dx:-100,dy:-100});
const limited=translateFloorSelection(f,[device('d1'),device('d2')],5000,5000);
assert.equal(limited.devices[1].x-limited.devices[0].x,140,'clamping preserves spacing');assert.equal(limited.devices[0].y-limited.devices[1].y,120);
assert.equal(limited.devices[1].x,2000);assert.equal(limited.devices[0].y,2000);
assert.equal(translateFloorSelection(f,group,0,0),f);assert.equal(translateFloorSelection(f,group,NaN,1),f);assert.equal(translateFloorSelection(f,[],10,20),f);
assert.deepEqual(translateFloorSelection(f,[...group,...group],40,80),moved,'duplicates never double-move');
assert.equal(uniqueSelection([...group,...group]).length,3);
const selected=selectInBox(f,{x:160,y:120},{x:520,y:550});
assert.ok(selected.some(i=>i.id==='living'));assert.ok(!selected.some(i=>i.id==='bed'),'partially covered rooms are excluded');assert.ok(selected.some(i=>i.id==='r1'));assert.ok(!selected.some(i=>i.id==='d3'));
assert.deepEqual(selectInBox(f,{x:520,y:550},{x:160,y:120}),selected,'either rectangle direction works');
assert.ok(!selectInBox(f,{x:0,y:0},{x:2000,y:2000},false,false).some(i=>i.type==='devices'||i.type==='routes'),'hidden layers are not selected');
assert.deepEqual(selectionBounds(f,[device('d1'),device('d2')]),{left:180,right:320,top:140,bottom:260});
assert.equal(JSON.stringify(f),snapshot,'source remains immutable');
const p=validatePlan(structuredClone(seed));p.buildings[0].floors[0]=moved;validatePlan(p);
console.log('PASS: group geometry, endpoint anchoring, shared bounds, immutability, box direction and visibility, room contents, dimensions and valid saved plan.');
