import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {seed,validatePlan} from '../lib/plan';
import {boards,boardSize,boardSizeIssue,boardDeleteIssue,circuitBoardIssue,findModulePlace,moveModule} from '../lib/board-size';
import {cabinetLayout,connectTerminals,connectionIssue,connectionPlan} from '../lib/cabinet';
import {pruneBoardLinks} from '../lib/board';
import {buildSchematic} from '../lib/schematic';
import {createPlanPdf} from '../lib/pdf-export';
import {materialList,searchPlan} from '../lib/plan-tools';

let p=validatePlan(structuredClone(seed));
assert.deepEqual(boardSize(p.buildings[0]),{rows:4,modulesPerRow:18});
assert.equal(boards(p.buildings[0]).length,1);
p.buildings[0].extraBoards=[{id:'sub',name:'Emeleti elosztó',rows:2,modulesPerRow:6}];
p.circuits.push({...p.circuits[0],id:'sub-c',name:'Emeleti dugaljak',board:'sub'});
p.modules.push({id:'sub-m',name:'Q-SUB',type:'MCB',building:'house',board:'sub',row:0,slot:0,width:1,circuit:''});
assert.doesNotThrow(()=>validatePlan(p),'same slot in different boards is valid');
assert.deepEqual(findModulePlace(p,'house',4,'sub'),{row:0,slot:1});
assert.equal(boardSizeIssue(p,'house',{rows:1,modulesPerRow:1},'sub'),null,'main board modules do not prevent shrinking the sub-board');
assert.ok(boardSizeIssue(p,'house',{rows:1,modulesPerRow:1}));
const main=cabinetLayout(p,'house'),sub=cabinetLayout(p,'house','sub');
assert.equal(main.devices.length,5);assert.equal(main.cards.length,3);
assert.equal(sub.devices.length,1);assert.equal(sub.cards.length,1);assert.equal(sub.rows.length,2);
const circuit={kind:'circuit' as const,id:'sub-c',port:'L'},terminal={kind:'module' as const,id:'sub-m',port:'L-out'};
assert.ok(connectionIssue(p,circuit,{...terminal,id:'m2'}));
const preview=connectionPlan(p,[circuit]);assert.equal(preview.modules.find(m=>m.id==='sub-m')!.circuit,'sub-c');
assert.equal(preview.modules.find(m=>m.id==='m0')!.circuit,'');
p=connectTerminals(p,circuit,terminal,'sub-wire');validatePlan(p);
assert.equal(buildSchematic(p,'house','multi').wireCount,0);
const diagram=buildSchematic(p,'house','multi','sub');assert.equal(diagram.wireCount,1);assert.equal(diagram.nodes.length,2);assert.equal(diagram.missing.length,2);
assert.ok(!diagram.nodes.some(n=>n.id==='m0'));
assert.ok(circuitBoardIssue(p,'sub-c',''));assert.ok(boardDeleteIssue(p,'house','sub'));
assert.throws(()=>moveModule(p,'sub-m',''),/Áthelyezés/);
const bad=structuredClone(p);bad.modules.find(m=>m.id==='sub-m')!.board='';assert.throws(()=>validatePlan(bad));pruneBoardLinks(bad);assert.equal(bad.boardWires.length,0);
const wrong=structuredClone(p);wrong.circuits.at(-1)!.board='absent';assert.throws(()=>validatePlan(wrong));
const other=structuredClone(p);other.modules.at(-1)!.circuit='c1';assert.throws(()=>validatePlan(other),/moduláramkör/);
const overlap=structuredClone(p);overlap.modules.push({...overlap.modules.at(-1)!,id:'dup'});assert.throws(()=>validatePlan(overlap),/átfedik/);
const oversize=structuredClone(p);oversize.modules.at(-1)!.slot=6;assert.throws(()=>validatePlan(oversize),/modulhely/);
const duplicate=structuredClone(p);duplicate.buildings[0].extraBoards!.push({...duplicate.buildings[0].extraBoards![0]});assert.throws(()=>validatePlan(duplicate),/azonosító/);
const missingPanel=structuredClone(p);missingPanel.buildings[0].floors[0].devices.find(d=>d.kind==='panel')!.board='absent';assert.throws(()=>validatePlan(missingPanel),/alaprajzi elosztó/);
const linked=structuredClone(p);linked.buildings[0].floors[0].devices.find(d=>d.kind==='panel')!.board='sub';
assert.deepEqual(validatePlan(JSON.parse(JSON.stringify(linked))),linked,'saving/import preserve board identities and panel references');
assert.ok(searchPlan(p,'Emeleti Q-SUB').some(r=>r.id==='sub-m'));
assert.ok(materialList(p).some(r=>r.location==='Családi ház / Emeleti elosztó'));
const empty=structuredClone(p);empty.modules=empty.modules.filter(m=>m.board!=='sub');empty.circuits=empty.circuits.filter(c=>c.board!=='sub');empty.boardWires=[];
assert.equal(boardDeleteIssue(empty,'house','sub'),null);empty.buildings[0].floors[0].devices.find(d=>d.kind==='panel')!.board='sub';assert.ok(boardDeleteIssue(empty,'house','sub'));
const movable=structuredClone(p);movable.boardWires=[];movable.modules.at(-1)!.circuit='';assert.equal(circuitBoardIssue(movable,'sub-c',''),null);moveModule(movable,'sub-m','');assert.equal(movable.modules.at(-1)!.slot,11);validatePlan(movable);
const font=readFileSync('public/fonts/NotoSans-Regular.ttf').toString('base64');
const mainPdf=createPlanPdf(p,{scope:'board',paper:'a4',buildingId:'house',floorId:'ground'},font);
const subPdf=createPlanPdf(p,{scope:'board',paper:'a4',buildingId:'house',floorId:'ground',boardId:'sub'},font);
assert.equal(mainPdf.getNumberOfPages(),4);assert.equal(subPdf.getNumberOfPages(),5);
const all=createPlanPdf(p,{scope:'all',paper:'a4',buildingId:'house',floorId:'ground'},font);
const oldAll=createPlanPdf(validatePlan(seed),{scope:'all',paper:'a4',buildingId:'house',floorId:'ground'},font);
assert.equal(all.getNumberOfPages()-oldAll.getNumberOfPages(),11,'all export includes sub-board layout, registers and both schematics');
console.log('PASS: legacy compatibility, independent board sizing/slots/circuits/wires, invalid references, cross-board guards, panel links, search, round-trip persistence, movement/deletion guards and PDF pagination.');
