import assert from 'node:assert/strict';
import {seed,validatePlan} from '../lib/plan';
import {placePanel,findLinkedPanel} from '../lib/panel-link';
import {moveRoutePoints,translateFloor,floorPoints,nodeHeight} from '../lib/geometry';
const plan=validatePlan(structuredClone(seed));
plan.plot.nodes.push({id:'site-panel',name:'Emeleti elosztó',kind:'panel',x:10,y:10,height:4.5});
const linked=placePanel(plan,'site-panel','upper');
assert.equal(linked.device.kind,'panel');assert.equal(linked.device.height,150);
assert.equal(plan.plot.nodes[0].deviceId,linked.device.id);
assert.equal(findLinkedPanel(plan,'site-panel')?.floor.id,'upper');
placePanel(plan,'site-panel','ground');assert.equal(linked.floor.devices.length,1);
linked.device.height=180;assert.equal(nodeHeight(plan.plot.nodes[0],plan),4.8);
assert.deepEqual(validatePlan(JSON.parse(JSON.stringify(plan))),plan);
const points=[{x:100,y:100},{x:300,y:100}],opts={startLocked:true,endLocked:true,maxX:2000,maxY:2000};
assert.deepEqual(moveRoutePoints(points,0,0,opts),points);
const shifted=moveRoutePoints(points,0,80,opts);
assert.deepEqual(shifted,[points[0],{x:100,y:180},{x:300,y:180},points[1]]);
assert.deepEqual(moveRoutePoints(points,40,80,{...opts,startLocked:false,endLocked:false}),[{x:140,y:180},{x:340,y:180}]);
assert.deepEqual(moveRoutePoints(points,0,80,{...opts,segment:0}),shifted);
const bent=[{x:100,y:100},{x:100,y:200},{x:300,y:200},{x:300,y:100}];
assert.deepEqual(moveRoutePoints(bent,0,40,{...opts,segment:1}),[bent[0],{x:100,y:240},{x:300,y:240},bent[3]]);
assert.deepEqual(moveRoutePoints(bent,30,0,{...opts,handle:1}),[bent[0],{x:130,y:200},bent[2],bent[3]]);
const f=plan.buildings[0].floors[0];
f.routes=[{...f.routes[0],points:[{x:0,y:0},{x:1,y:1}],startId:'p1',endId:'d1'}];
const before=floorPoints(f.routes[0],f),moved=translateFloor(f,{type:'routes',id:f.routes[0].id,dx:0,dy:40});
assert.equal(moved.routes[0].points.length,4);assert.deepEqual(floorPoints(moved.routes[0],moved)[0],before[0]);assert.deepEqual(floorPoints(moved.routes[0],moved).at(-1),before[1]);
assert.equal(f.routes[0].points.length,2);assert.equal(moved.routes[0].startId,'p1');assert.equal(moved.routes[0].endId,'d1');
console.log('PASS: panel placement/link/height/roundtrip, direct and segmented route drag, locked endpoints and immutable drag preview.');
