import assert from 'node:assert/strict';
import {seed,validatePlan} from '../lib/plan';
import {materialList,materialsCsv,searchPlan,withAllowance} from '../lib/plan-tools';
const plan=validatePlan(structuredClone(seed)),f=plan.buildings[0].floors[0];
f.routes=[{id:'test',name:'Próba vezeték',points:[{x:0,y:0},{x:400,y:0}],mode:'inside',circuit:'',cable:'3 × 2,5 mm²',planeHeight:260,startHeight:30,endHeight:110}];
plan.plot.nodes=[{id:'linked',name:'Kapcsolt',kind:'panel',x:1,y:1,height:1.5,deviceId:'p1'},{id:'meter',name:'Mérő',kind:'meter',x:11,y:1,height:1.5}];
plan.plot.routes=[{id:'s',name:'Földkábel',from:'linked',to:'meter',via:[],level:-.7,mode:'underground',cable:'5 × 10 mm²'}];
const rows=materialList(plan),inside=rows.find(r=>r.category==='Kábel'&&r.location!=='Telek')!,site=rows.find(r=>r.category==='Kábel'&&r.location==='Telek')!;
assert.ok(Math.abs(inside.quantity-13.8)<1e-9);
assert.ok(Math.abs(site.quantity-14.4)<1e-9);
assert.equal(rows.filter(r=>r.category==='Telki pont').reduce((s,r)=>s+r.quantity,0),1);
assert.equal(rows.filter(r=>r.category==='Szerelvény').reduce((s,r)=>s+r.quantity,0),8);
assert.equal(materialList(plan,'garage').length,0);
assert.ok(!materialList(plan,'house').some(r=>r.location==='Telek'));
assert.ok(Math.abs(withAllowance(inside,10)-15.18)<1e-9);
assert.equal(withAllowance(inside,-10),inside.quantity);
assert.equal(withAllowance({...inside,unit:'db'},10),inside.quantity);
assert.equal(searchPlan(plan,'haloszoba')[0].title,'Hálószoba');
assert.equal(searchPlan(plan,'Dolgozoszoba')[0].floorId,'upper');
assert.ok(searchPlan(plan,'D-01')[0].type==='devices');
assert.equal(searchPlan(plan,'Főkapcsoló')[0].type,'modules');
assert.equal(searchPlan(plan,'   ').length,0);
const csv=materialsCsv([{...inside,item:'=HYPERLINK("bad")',location:'Név;idézet"'}],10);
assert.ok(csv.startsWith('\uFEFF'));
assert.ok(csv.includes('"\'=HYPERLINK(""bad"")"'));
assert.ok(csv.includes('"Név;idézet"""'));
assert.ok(csv.includes('"15,18"'));
console.log('PASS: 3D cable quantities, allowance, scope, linked-panel deduplication, accent-insensitive search, floor targeting and safe Hungarian CSV.');
