import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {saveWithHistory,HISTORY_LIMIT} from '../lib/plan-versions';
import type {Database} from '../db/database';
const sql=new DatabaseSync(':memory:');
sql.exec("CREATE TABLE plans(id TEXT PRIMARY KEY,data TEXT,revision INTEGER,updated_at TEXT,state TEXT DEFAULT 'active'); CREATE TABLE plan_versions(project_id TEXT,revision INTEGER,data TEXT,saved_at TEXT,PRIMARY KEY(project_id,revision));");
const db:Database={kind:'d1',async first<T>(s:string,p:(string|number|null)[]=[]){return sql.prepare(s).get(...p) as T||null},async all<T>(s:string,p:(string|number|null)[]=[]){return sql.prepare(s).all(...p) as T[]},async run(s,p=[]){return Number(sql.prepare(s).run(...p).changes)},async batch(statements){sql.exec('BEGIN');try{const results=statements.map(s=>Number(sql.prepare(s.sql).run(...s.params).changes));sql.exec('COMMIT');return results}catch(e){sql.exec('ROLLBACK');throw e}}};
const record=(key='owner:a')=>sql.prepare('SELECT * FROM plans WHERE id=?').get(key)!;
const history=(key='owner:a')=>sql.prepare('SELECT * FROM plan_versions WHERE project_id=? ORDER BY revision DESC').all(key);
sql.prepare('INSERT INTO plans(id,data,revision,updated_at) VALUES (?,?,?,?)').run('owner:a','original',1,'first-time');
sql.prepare('INSERT INTO plans(id,data,revision,updated_at) VALUES (?,?,?,?)').run('owner:b','other',1,'other-time');
assert.equal(await saveWithHistory(db,'owner:a','second',1,'second-time'),1);
assert.equal(record().data,'second');assert.equal(history()[0].data,'original');assert.equal(history()[0].saved_at,'first-time');
assert.equal(await saveWithHistory(db,'owner:a','stale',1,'ignored'),0);assert.equal(record().data,'second');assert.equal(history().length,1);
sql.exec("CREATE TRIGGER fail_save BEFORE UPDATE ON plans WHEN NEW.data='fail' BEGIN SELECT RAISE(ABORT,'injected failure'); END;");
await assert.rejects(saveWithHistory(db,'owner:a','fail',2,'ignored'));assert.equal(record().data,'second');assert.equal(history().length,1,'failed update rolls back snapshot');
sql.exec('DROP TRIGGER fail_save');
assert.deepEqual((await Promise.all([saveWithHistory(db,'owner:a','winner',2,'third-time'),saveWithHistory(db,'owner:a','loser',2,'ignored')])).sort(),[0,1]);
assert.equal(record().data,'winner');assert.equal(history().length,2);
sql.exec("UPDATE plans SET state='trash',revision=revision+1 WHERE id='owner:a'");
assert.equal(await saveWithHistory(db,'owner:a','inactive',4,'ignored'),0);assert.equal(history().length,2);
sql.exec("UPDATE plans SET state='active',revision=revision+1 WHERE id='owner:a'");
for(let i=5;i<42;i++)assert.equal(await saveWithHistory(db,'owner:a','version-'+i,i,'time-'+i),1);
assert.equal(history().length,HISTORY_LIMIT);assert.equal(history()[0].revision,41);assert.equal(history().at(-1)!.revision,12);
assert.equal(record('owner:b').data,'other');assert.equal(history('owner:b').length,0);
sql.close();console.log('PASS: atomic snapshot/update, rollback, stale/concurrent writes, inactive plans, 30-version retention, original timestamps, owner isolation.');
