import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {seed,validatePlan} from '../lib/plan';
import {blankProject,removeStructure,projectKey,validProjectId} from '../lib/projects';
import {createPlanPdf} from '../lib/pdf-export';
const blank=validatePlan(blankProject('Új projekt'));
assert.equal(blank.buildings.length,1);assert.equal(blank.buildings[0].floors[0].rooms.length,0);assert.equal(blank.circuits.length,0);
const p=validatePlan(structuredClone(seed)),before=structuredClone(p);
p.plot.nodes.push({id:'linked',kind:'panel',name:'Elosztó',x:5,y:5,height:0,deviceId:'p1'});
p.plot.nodes.push({id:'supply',kind:'supply',name:'Bekötés',x:0,y:0,height:0});
p.plot.routes.push({id:'site-route',name:'Kötés',from:'linked',to:'supply',via:[],level:-.7,mode:'underground',cable:'5x10'});
removeStructure(p,'house','ground');
assert.equal(p.buildings[0].floors.length,1);assert.equal(p.plot.nodes[0].deviceId,'');assert.equal(p.plot.nodes[0].height,1.5);assert.equal(p.plot.routes.length,1);validatePlan(p);
removeStructure(p,'house');assert.equal(p.circuits.length,0);assert.equal(p.modules.length,0);assert.equal(p.buildings[0].id,'garage');validatePlan(p);
removeStructure(p,'garage','garagefloor');assert.equal(p.buildings[0].floors.length,0);validatePlan(p);
const font=readFileSync('public/fonts/NotoSans-Regular.ttf').toString('base64');
assert.ok(createPlanPdf(p,{scope:'all',paper:'a4',buildingId:'garage',floorId:''},font).getNumberOfPages()>0);
removeStructure(p,'garage');assert.equal(p.buildings.length,0);validatePlan(p);
assert.ok(createPlanPdf(p,{scope:'all',paper:'a4',buildingId:'',floorId:''},font).getNumberOfPages()>0);
assert.throws(()=>createPlanPdf(p,{scope:'floor',paper:'a4',buildingId:'',floorId:''},font),/Nincs exportálható szint/);
assert.equal(before.buildings.length,2);assert.equal(before.buildings[0].floors[0].devices.length,8);
assert.equal(projectKey('a','default'),'account:a');assert.notEqual(projectKey('a',blank.buildings[0].id),projectKey('b',blank.buildings[0].id));assert.ok(validProjectId(blank.buildings[0].id));assert.ok(!validProjectId('default:project:%'));
console.log('PASS: blank projects, floor/building deletion, orphan-free references, empty-plan validation and PDF exports, owner-scoped keys.');
