import assert from 'node:assert/strict';
import {seed,validatePlan} from '../lib/plan';
import {routeRegister,filterRouteRegister,type RouteFilters} from '../lib/route-register';
const p=validatePlan(structuredClone(seed)),f=p.buildings[0].floors[0];
const filters:RouteFilters={building:'all',circuit:'all',mode:'all',query:'',freeOnly:false,sort:'name'};
const snapshot=JSON.stringify(p),rows=routeRegister(p);
assert.equal(rows.length,2);assert.equal(rows.find(r=>r.target.id==='r1')!.total,23.4);assert.ok(Math.abs(rows.find(r=>r.target.id==='r1')!.vertical-3.4)<1e-10);
assert.equal(rows.find(r=>r.target.id==='r1')!.start,'E-01');assert.equal(rows.find(r=>r.target.id==='r1')!.end,'D-01');assert.equal(rows[0].freeEnds,0);
assert.equal(filterRouteRegister(rows,{...filters,query:'vilagitas'}).length,1);
assert.equal(filterRouteRegister(rows,{...filters,query:'nappali 2,5'}).length,1);
assert.equal(filterRouteRegister(rows,{...filters,query:'E-01'}).length,1);
assert.equal(filterRouteRegister(rows,{...filters,mode:'outside'})[0].target.id,'r2');
assert.equal(filterRouteRegister(rows,{...filters,building:'garage'}).length,0);
assert.equal(filterRouteRegister(rows,{...filters,circuit:'c1'})[0].target.id,'r1');
assert.equal(filterRouteRegister(rows,{...filters,freeOnly:true}).length,0);
assert.deepEqual(filterRouteRegister(rows,{...filters,sort:'longest'}).map(r=>r.target.id),['r1','r2']);
assert.deepEqual(filterRouteRegister(rows,{...filters,sort:'shortest'}).map(r=>r.target.id),['r2','r1']);
assert.equal(JSON.stringify(p),snapshot);
f.routes[0].startId='';f.routes[0].circuit='';f.routes[0].cable='   ';
let changed=routeRegister(p);const free=filterRouteRegister(changed,{...filters,circuit:'unassigned',freeOnly:true});assert.equal(free.length,1);assert.equal(free[0].freeEnds,1);assert.equal(free[0].cable,'Nincs kábeljelölés');
// Linked device coordinates and heights, rather than stale route endpoints, are used.
f.devices.find(d=>d.id==='d1')!.x=220;f.devices.find(d=>d.id==='d1')!.height=80;
changed=routeRegister(p);assert.equal(changed[0].target.x,350);assert.ok(Math.abs(changed[0].vertical-1.8)<1e-10);
p.buildings[0].floors[1].routes.push({...f.routes[0],id:'up-route',startId:'',endId:'',name:'Emeleti tartalék'});assert.equal(routeRegister(p).find(r=>r.target.id==='up-route')!.target.floorId,'upper');
p.plot.nodes=[{id:'a',kind:'supply',name:'Bekötési pont',x:1,y:1,height:0},{id:'b',kind:'meter',name:'Villanyóra',x:5,y:1,height:1}];p.plot.routes=[{id:'site',name:'Telki kábel',from:'a',to:'b',via:[],level:-.7,mode:'underground',cable:'5x10'}];assert.equal(routeRegister(p).length,4);
assert.equal(routeRegister({...p,buildings:[]}).length,1,'a plot-only project retains its routes');
let site=routeRegister(p).find(r=>r.target.id==='site')!;
assert.equal(site.target.type,'siteRoutes');assert.equal(site.kind,'plot');assert.equal(site.horizontal,4);assert.equal(site.vertical,2.4);assert.equal(site.total,6.4);assert.equal(site.plane,-.7);assert.equal(site.startHeight,0);assert.equal(site.endHeight,1);
assert.equal(filterRouteRegister(routeRegister(p),{...filters,building:'plot'}).length,1);
assert.equal(filterRouteRegister(routeRegister(p),{...filters,building:'floors'}).length,3);
assert.equal(filterRouteRegister(routeRegister(p),{...filters,building:'plot',freeOnly:true}).length,0);
assert.equal(filterRouteRegister(routeRegister(p),{...filters,building:'plot',circuit:'unassigned'}).length,0,'plot connections are not unassigned floor circuits');
assert.equal(filterRouteRegister(routeRegister(p),{...filters,mode:'underground',query:'villanyora fold'}).length,1);
// Two linked buildings: use real floor elevation + mounting height and count the route once.
p.buildings[0].extraBoards=[{id:'sub',name:'Emeleti szekrény',rows:2,modulesPerRow:12}];
p.buildings[0].floors[1].devices.push({id:'up-panel',name:'E-02',kind:'panel',board:'sub',x:10,y:10,height:150,angle:0,circuit:''});
p.buildings[1].floors[0].devices.push({id:'garage-panel',name:'G-E',kind:'panel',x:20,y:20,height:100,angle:0,circuit:''});
p.plot.nodes[0].deviceId='up-panel';p.plot.nodes[1].deviceId='garage-panel';p.plot.routes[0].via=[{x:1,y:4},{x:5,y:4}];
site=routeRegister(p).find(r=>r.kind==='plot')!;assert.equal(site.startHeight,4.5);assert.equal(site.endHeight,1);assert.equal(site.horizontal,10);assert.equal(site.vertical,6.9);assert.equal(site.total,16.9);
assert.deepEqual(site.buildingIds,['house','garage']);assert.match(site.start,/Emeleti szekrény/);
assert.equal(filterRouteRegister(routeRegister(p),{...filters,building:'garage'}).length,1);
assert.equal(filterRouteRegister(routeRegister(p),{...filters,building:'house'}).length,4);
assert.equal(filterRouteRegister(routeRegister(p),{...filters,query:'emeleti szekreny villanyora'}).length,1);
p.plot.routes[0].mode='overhead';p.plot.routes[0].level=6;p.plot.nodes[1].x=9;
site=routeRegister(p).find(r=>r.kind==='plot')!;assert.equal(site.vertical,6.5);assert.equal(site.horizontal,12);
assert.equal(filterRouteRegister(routeRegister(p),{...filters,mode:'overhead'}).length,1);
p.plot.routes[0].mode='surface';assert.equal(filterRouteRegister(routeRegister(p),{...filters,mode:'surface'}).length,1);
const finalSnapshot=JSON.stringify(p);routeRegister(p);assert.equal(JSON.stringify(p),finalSnapshot);
assert.deepEqual(routeRegister({...p,buildings:[],plot:{...p.plot,nodes:[],routes:[]}}),[]);
console.log('PASS: floor and plot scope, linked buildings, height/geometry updates, all modes, search and sorting, circuit/free-end semantics, plot-only plans, navigation targets and immutability.');
