import assert from 'node:assert/strict';
import {seed,validatePlan} from '../lib/plan';
import {floorPoints,floorLength} from '../lib/geometry';
import {copySource,copyStructure,suggestRoomOffset,type StructureCopyOptions} from '../lib/structure-copy';
const plan=validatePlan(structuredClone(seed)),floor=plan.buildings[0].floors[0];
floor.walls=[{id:'w',a:{x:200,y:200},b:{x:300,y:200}},{id:'cross',a:{x:200,y:200},b:{x:700,y:200}}];
floor.dimensions=[{id:'dim',name:'Szélesség',a:{x:200,y:200},b:{x:300,y:200},offset:40,mode:'aligned'}];
floor.background={assetId:crypto.randomUUID(),name:'Háttér',x:0,y:0,w:1000,h:720,opacity:.5,visible:true,calibrated:true};
floor.devices.find(d=>d.id==='p1')!.height=145;
const original=JSON.stringify(plan);
const opts:StructureCopyOptions={buildingId:'house',floorId:'ground',name:'Másolt szint',elevation:6,dx:0,dy:0,contents:true,keepCircuits:false,panels:false,background:true};
const result=copyStructure(plan,opts),copy=result.plan.buildings[0].floors.at(-1)!;
assert.equal(result.plan.buildings[0].floors.length,3);assert.equal(copy.elevation,6);assert.equal(copy.name,'Másolt szint');
assert.equal(copy.devices.length,floor.devices.length-1);assert.ok(!copy.devices.some(d=>d.kind==='panel'));
assert.equal(copy.routes[0].startId,'');assert.equal(copy.routes[0].startHeight,145,'omitted endpoint keeps actual mounting height');
const copiedD=copy.devices.find(d=>d.name==='D-01')!;assert.equal(copy.routes[0].endId,copiedD.id);assert.notEqual(copiedD.id,'d1');
assert.deepEqual(floorPoints(copy.routes[0],copy),floorPoints(floor.routes[0],floor));
assert.equal(floorLength(copy.routes[0],copy).total,floorLength(floor.routes[0],floor).total);
assert.ok([...copy.devices,...copy.routes].every(d=>d.circuit===''));
assert.deepEqual(copy.background,floor.background);assert.notEqual(copy.background,floor.background);
assert.deepEqual(result.plan.plot,plan.plot);assert.deepEqual(result.plan.modules,plan.modules);assert.deepEqual(result.plan.boardWires,plan.boardWires);assert.deepEqual(result.plan.circuits,plan.circuits);
assert.deepEqual(copy.dimensions![0].a,floor.dimensions[0].a);assert.notEqual(copy.dimensions![0].id,'dim');
const retained=copyStructure(plan,{...opts,keepCircuits:true,panels:true,background:false}).plan.buildings[0].floors.at(-1)!;
assert.equal(retained.devices.length,floor.devices.length);assert.equal(retained.devices[0].circuit,'c1');assert.equal(retained.routes[0].startId,retained.devices.find(d=>d.kind==='panel')!.id);assert.equal(retained.background,undefined);
const roomOpts={...opts,roomId:'living',name:'Új nappali',dx:680,dy:40};
const src=copySource(plan,roomOpts);assert.equal(src.items.filter(i=>i.type==='rooms').length,1);assert.ok(!src.items.some(i=>i.id==='cross'));assert.ok(src.items.some(i=>i.id==='d2'),'wall-bound devices are included');
const room=copyStructure(plan,roomOpts),roomFloor=room.plan.buildings[0].floors[0];
assert.equal(room.plan.buildings[0].floors.length,2);assert.equal(roomFloor.rooms.at(-1)!.x,860);assert.equal(roomFloor.rooms.at(-1)!.y,180);assert.equal(roomFloor.rooms.at(-1)!.name,'Új nappali');
assert.equal(roomFloor.walls.at(-1)!.a.x,880);assert.equal(roomFloor.dimensions!.at(-1)!.a.x,880);
const addedRoute=roomFloor.routes[floor.routes.length];assert.equal(addedRoute.startId,'');assert.equal(addedRoute.startHeight,145);
assert.ok(room.items.some(i=>i.type==='devices'&&i.id===addedRoute.endId));
assert.deepEqual(addedRoute.points,floorPoints(floor.routes[0],floor).map(p=>({x:p.x+680,y:p.y+40})));
assert.ok(roomFloor.devices.slice(floor.devices.length).every(d=>!floor.devices.some(s=>s.id===d.id||s.name===d.name)));
const bare=copyStructure(plan,{...roomOpts,contents:false});assert.equal(bare.items.length,1);assert.deepEqual(bare.plan.buildings[0].floors[0].devices,floor.devices);
const shell=copyStructure(plan,{...opts,contents:false}).plan.buildings[0].floors.at(-1)!;assert.equal(shell.routes.length,0);assert.equal(shell.devices.length,0);assert.equal(shell.walls.length,2);assert.equal(shell.dimensions!.length,1);
assert.throws(()=>copyStructure(plan,{...roomOpts,dx:2000}),/túlnyúlna/);assert.throws(()=>copyStructure(plan,{...roomOpts,dx:NaN}),/eltolást/);assert.throws(()=>copyStructure(plan,{...opts,name:' '}),/név/);assert.throws(()=>copyStructure(plan,{...opts,elevation:101}),/szintmagasság/);assert.throws(()=>copyStructure(plan,{...roomOpts,roomId:'missing'}),/szoba/);
const full=structuredClone(plan);while(full.buildings[0].floors.length<30)full.buildings[0].floors.push({...structuredClone(floor),id:crypto.randomUUID()});assert.throws(()=>copyStructure(full,opts),/30 szint/);
const fullRooms=structuredClone(plan);while(fullRooms.buildings[0].floors[0].rooms.length<200)fullRooms.buildings[0].floors[0].rooms.push({...floor.rooms[0],id:crypto.randomUUID()});assert.throws(()=>copyStructure(fullRooms,{...roomOpts,contents:false}),/200 szoba/);
const offset=suggestRoomOffset(floor,'living');assert.ok(offset.dx>0||offset.dy>0);assert.ok(floor.rooms[0].x+offset.dx+floor.rooms[0].w<=2000);
assert.equal(JSON.stringify(plan),original,'copying and failures never mutate source');
copy.devices[0].height=99;assert.equal(floor.devices[0].height,30,'copies are independent');
validatePlan(room.plan);validatePlan(result.plan);validatePlan(copyStructure(result.plan,{...opts,floorId:copy.id}).plan);
console.log('PASS: independent IDs, internal and omitted endpoints/heights, room boundary scope, structure-only copy, circuits/panels/background options, bounds/capacity validation and repeated copy round trip.');
