import assert from 'node:assert/strict';
import {captureTemplate,insertTemplate,validateTemplate,validateTemplateLibrary} from '../lib/templates';
import {seed,validatePlan} from '../lib/plan';
import {newOpening} from '../lib/architecture';
const plan=validatePlan(structuredClone(seed)),floor=plan.buildings[0].floors[0];
floor.rooms[0].openings=[newOpening('door')];floor.rooms[0].thickness=30;
floor.routes[0].startId='p1';floor.routes[0].endId='d1';
const original=JSON.stringify(plan);
const room=captureTemplate(plan,'house','ground','living','Nappali');
assert.equal(room.kind,'room');assert.equal(room.floor.rooms.length,1);
assert.ok(room.floor.devices.length>0);assert.ok(room.floor.devices.every(d=>!d.circuit&&d.kind!=='panel'&&!d.board));
assert.ok(room.floor.routes.every(r=>!r.circuit));
const whole=captureTemplate(plan,'house','ground',undefined,'Teljes szint');
assert.equal(whole.floor.routes[0].startId,'');assert.equal(whole.floor.routes[0].endId,'d1');assert.equal(whole.floor.routes[0].startHeight,150);
const without=captureTemplate(plan,'house','ground','living','Üres szoba',false);assert.equal(without.floor.devices.length,0);assert.equal(without.floor.routes.length,0);assert.equal(without.floor.rooms[0].openings?.length,1);
const options={buildingId:'garage',floorId:'garagefloor',name:'Új szoba',x:900,y:200,elevation:6,contents:true};
const inserted=insertTemplate(plan,room,options),target=inserted.plan.buildings[1].floors[0];
const newRoom=target.rooms.at(-1)!;assert.equal(newRoom.x,900);assert.equal(newRoom.y,200);assert.equal(newRoom.thickness,30);assert.notEqual(newRoom.openings![0].id,room.floor.rooms[0].openings![0].id);
assert.equal(target.devices.length,room.floor.devices.length);assert.equal(inserted.plan.circuits.length,plan.circuits.length);assert.equal(inserted.plan.modules.length,plan.modules.length);
assert.equal(JSON.stringify(plan),original,'capture and insert never mutate original');
const repeated=insertTemplate(inserted.plan,room,{...options,x:1300});validatePlan(repeated.plan);
const newFloor=insertTemplate(plan,whole,{...options,name:'Hatodik',elevation:6});assert.equal(newFloor.plan.buildings[1].floors.length,2);
const nf=newFloor.plan.buildings[1].floors[1];assert.equal(nf.elevation,6);assert.equal(nf.routes[0].startId,'');assert.ok(nf.devices.some(d=>d.id===nf.routes[0].endId));assert.equal(nf.routes[0].startHeight,150);
assert.equal(insertTemplate(plan,whole,{...options,contents:false}).plan.buildings[1].floors[1].devices.length,0);
assert.throws(()=>insertTemplate(plan,room,{...options,x:1950}));assert.throws(()=>insertTemplate(plan,room,{...options,x:NaN}));
assert.throws(()=>insertTemplate(plan,whole,{...options,elevation:101}));assert.throws(()=>insertTemplate(plan,{...room,archived:true},options));
assert.throws(()=>validateTemplateLibrary([room,room]));assert.throws(()=>validateTemplateLibrary(Array(31).fill(room)));
const bad=structuredClone(room);bad.floor.devices[0].circuit='c1';assert.throws(()=>validateTemplate(bad));
const dangling=structuredClone(whole);dangling.floor.routes[0].endId='missing';assert.throws(()=>validateTemplate(dangling));
assert.deepEqual(validateTemplate(JSON.parse(JSON.stringify(whole))),whole);
console.log('PASS: room/floor capture, independent IDs, cross-building insertion, endpoint remapping and heights, empty-content options, openings, immutable sources, bounds, forbidden references, archived/duplicate/over-limit templates, JSON round-trip.');
