import {billingProfile,invoiceConfig,invoiceReady} from '@/lib/invoicing';
import {refreshSubscriptions,subscriptionPortal} from '@/lib/stripe-subscriptions';
import {getBillingConfig,isAdmin} from '@/lib/billing';
import {withDatabase} from '@/db/database';
import {accountFromHeaders,privateHeaders,sameOrigin} from '@/lib/auth';
import {billingStatus} from '@/lib/billing';
import {checkout,confirmCheckout} from '@/lib/stripe-payments';
export async function GET(req:Request){try{return await withDatabase(async db=>{const user=await accountFromHeaders(db,req.headers);if(!user)return Response.json({error:'Jelentkezz be a projekthelyek megtekintéséhez.'},{status:401,headers:privateHeaders});return Response.json(await billingStatus(db,user),{headers:privateHeaders})})}catch{return Response.json({error:'A fizetési adatok most nem érhetők el.'},{status:503,headers:privateHeaders})}}
export async function POST(req:Request){try{const raw=await req.text();if(!sameOrigin(req))return Response.json({error:'Érvénytelen kérés.'},{status:403,headers:privateHeaders});if(raw.length>2000)throw Error('Túl nagy kérés.');const data=JSON.parse(raw);return await withDatabase(async db=>{const user=await accountFromHeaders(db,req.headers);if(!user)return Response.json({error:'A vásárláshoz jelentkezz be.'},{status:401,headers:privateHeaders});if(data.action==='portal'||data.action==='refresh'){const {config}=await getBillingConfig(db),mode=isAdmin(user)?config.mode:'live';if(data.action==='portal')return Response.json({url:await subscriptionPortal(db,user,mode)},{headers:privateHeaders});await refreshSubscriptions(db,user.userId,mode);return Response.json(await billingStatus(db,user),{headers:privateHeaders})}if(data.action==='confirm'&&typeof data.sessionId==='string'&&/^cs_[a-zA-Z0-9_]{10,200}$/.test(data.sessionId)){const confirmed=await confirmCheckout(db,user,data.sessionId);return Response.json({confirmed,...await billingStatus(db,user)},{headers:privateHeaders})}if(data.action!=='checkout'||typeof data.requestId!=='string'||!/^[a-f0-9-]{36}$/i.test(data.requestId))throw Error('Érvénytelen kérés.');if(data.kind!==undefined&&!['project','subscription'].includes(data.kind))throw Error('Érvénytelen csomag.');const profile=await billingProfile(db,user.userId);if(!profile)throw Error('Előbb mentsd a számlázási adataidat.');const {config:invoiceSettings}=await invoiceConfig(db),{config:paymentSettings}=await getBillingConfig(db);if(!invoiceReady(invoiceSettings,paymentSettings.mode))throw Error('Az automatikus számlázás még nincs beállítva; új vásárlás most nem indítható.');const url=await checkout(db,user,data.requestId,data.kind||'project',profile);return Response.json({url},{headers:privateHeaders})})}catch(e){return Response.json({error:e instanceof Error&&!(e as {type?:string}).type?e.message:'A Stripe-fizetés indítása vagy ellenőrzése nem sikerült. Próbáld újra.'},{status:400,headers:privateHeaders})}}
