"use client";
import {useEffect,useRef,useState} from 'react';
import {KeyRound,MailCheck,ArrowLeft} from 'lucide-react';
export default function AccountRecovery({kind}:{kind:'reset'|'verify'}){
 const [token,setToken]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[ready,setReady]=useState(false);const loaded=useRef(false);
 useEffect(()=>{if(loaded.current)return;loaded.current=true;const value=new URLSearchParams(location.hash.slice(1)).get('token')||'';setToken(value);history.replaceState(null,'',location.pathname);try{const theme=localStorage.getItem('shockcraft-theme');document.documentElement.dataset.theme=(theme?theme==='dark':matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light'}catch{}setReady(true)},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setError('');setMessage('');if(kind==='reset'&&token&&(password!==repeat||password.length<12||new TextEncoder().encode(password).length>72)){setError('Adj meg két egyező, legalább 12 karakteres, legfeljebb 72 bájtos jelszót.');return}setBusy(true);try{const action=token?kind:'forgot';const r=await fetch('/api/account-email/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(token?{token,...(kind==='reset'?{password}:{})}:{email})});const d=await r.json() as {error?:string;message:string};if(!r.ok)throw Error(d.error);setMessage(d.message);if(token){setDone(true);setToken('');setPassword('');setRepeat('')}}catch(e){setError(e instanceof Error?e.message:'A művelet nem sikerült.')}finally{setBusy(false)}}
 return <main className="account-page"><a className="account-back" href="/tervezo?auth=login"><ArrowLeft size={18}/> Vissza a tervezőhöz</a><section className="account-card"><div className="account-symbol">{kind==='reset'?<KeyRound/>:<MailCheck/>}</div><span className="account-eyebrow">SHOCKCRAFT · SAJÁT FIÓK</span><h1>{kind==='reset'?(token?'Új jelszó megadása':'Jelszó visszaállítása'):'E-mail-cím megerősítése'}</h1>{!ready?<p>Betöltés…</p>:done?<><p className="billing-notice" role="status">{message}</p><a className="auth-link" href="/tervezo?auth=login">Vissza a bejelentkezéshez</a></>:kind==='verify'&&!token?<><p>A megerősítéshez nyisd meg az e-mailben kapott hivatkozást.</p><p>Új levelet a tervezőben, a <strong>Fiókom</strong> ablakban kérhetsz.</p></>:<><p>{kind==='verify'?'Az alábbi gombbal igazolhatod, hogy ez az e-mail-cím hozzád tartozik.':token?'Az új jelszó mentése után minden korábbi bejelentkezés megszűnik. A terveid megmaradnak.':'Add meg a fiókod e-mail-címét. A levélben kapott linkkel 30 percen belül új jelszót állíthatsz be.'}</p><form onSubmit={submit} className="auth-form">{kind==='reset'&&(token?<><label className="field"><span>Új jelszó</span><input type="password" autoComplete="new-password" required minLength={12} maxLength={72} value={password} disabled={busy} onChange={e=>setPassword(e.target.value)}/></label><label className="field"><span>Új jelszó ismét</span><input type="password" autoComplete="new-password" required minLength={12} maxLength={72} value={repeat} disabled={busy} onChange={e=>setRepeat(e.target.value)}/></label><p className="auth-note">Legalább 12 karakter; használhatsz hosszú jelmondatot.</p></>:<label className="field"><span>E-mail-cím</span><input type="email" autoComplete="email" required maxLength={254} value={email} disabled={busy} onChange={e=>setEmail(e.target.value)}/></label>)}{error&&<p className="auth-error" role="alert">{error}</p>}{message&&<p className="billing-notice" role="status">{message}</p>}<button className="primary" type="submit" disabled={busy}>{busy?'Folyamatban…':kind==='verify'?'E-mail-cím megerősítése':token?'Új jelszó mentése':'Visszaállító levél kérése'}</button></form>{token&&kind==='reset'&&<button className="textbutton" disabled={busy} onClick={()=>{setToken('');setError('')}}>Lejárt a link? Új levelet kérek</button>}</>}</section></main>
}
