"use client";
import {useEffect,useState} from 'react';
import {Switch} from './ui/switch';
type Settings={enabled:boolean;from:string;keyConfigured:boolean;revision:number;encryptionReady:boolean};
export default function AdminEmail(){
 const [data,setData]=useState<Settings|null>(null),[apiKey,setKey]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function load(){const r=await fetch('/api/admin/email',{cache:'no-store'});const d=await r.json() as Settings & {error?:string};if(!r.ok)throw Error(d.error);setData(d)}
 useEffect(()=>{void load().catch(e=>setError(e.message))},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(!data||busy)return;setBusy(true);setMessage('');setError('');try{const r=await fetch('/api/admin/email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:data.enabled,from:data.from,revision:data.revision,apiKey})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setKey('');await load();setMessage('A levélküldés beállításait elmentettük. A Fiókom ablakban kérhetsz megerősítő levelet a működés kipróbálásához.')}catch(e){setError(e instanceof Error?e.message:'A mentés nem sikerült.')}finally{setBusy(false)}}
 return <section className="admin-card" id="email"><h2>Fióklevelek · Resend</h2><p>E-mail-cím megerősítése és elfelejtett jelszó visszaállítása. Regisztráció után automatikusan megerősítő levelet küldünk, ha a küldés be van kapcsolva.</p>{error&&<p className="auth-error" role="alert">{error}</p>}{message&&<p className="billing-notice" role="status">{message}</p>}{!data?<button onClick={()=>void load().catch(e=>setError(e.message))}>Beállítások betöltése</button>:<form onSubmit={save}><div className="admin-controls"><label className="field"><span>Feladó e-mail-címe</span><input type="email" name="resend-sender" autoComplete="off" maxLength={254} placeholder="pelda@sajat-domain.hu" value={data.from} disabled={busy} onChange={e=>setData({...data,from:e.target.value})}/></label><label className="field"><span>Resend API-kulcs · {data.keyConfigured?'beállítva':'még nincs megadva'}</span><input type="password" name="resend-api-key" autoComplete="new-password" data-1p-ignore="true" data-lpignore="true" maxLength={500} placeholder="re_…" value={apiKey} disabled={busy} onChange={e=>setKey(e.target.value)}/></label></div><label className="billing-switch"><span>Fióklevelek küldése</span><Switch aria-label="Fióklevelek küldése" checked={data.enabled} disabled={busy} onCheckedChange={enabled=>setData({...data,enabled})}/></label><p className="auth-note">Az üres kulcsmező megtartja a mentett kulcsot. A titkos kulcsot mentés után nem jelenítjük meg.</p>{!data.encryptionReady&&<p className="auth-error">A szerveren előbb be kell állítani a BILLING_ENCRYPTION_KEY titkosítókulcsot.</p>}<div className="project-actions"><button className="primary" disabled={busy||!data.encryptionReady}>{busy?'Mentés…':'Levélküldés mentése'}</button></div></form>}<ol><li>A <a href="https://resend.com/domains" target="_blank" rel="noopener noreferrer">Resendben</a> add hozzá és igazold a saját feladói domainedet a kért DNS-bejegyzésekkel.</li><li>Hozz létre levélküldési API-kulcsot, majd itt add meg a kulcsot és a domainhez tartozó feladói címet.</li><li>Kapcsold be a küldést, mentsd a beállításokat, és kérj megerősítő levelet a saját fiókodban.</li></ol><p>A beállítások mentése önmagában még nem igazolja a kézbesítést. A Resend levelezési naplójában ellenőrizheted az elutasított vagy visszapattant leveleket.</p></section>
}
