"use client";
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
export type BillingStatus={price:number;available:number;free:number;paid:number;mode:'test'|'live';ready:boolean;admin:boolean};
export function BillingDialog({open,onOpenChange,account,prepare,leave}:{open:boolean;onOpenChange:(v:boolean)=>void;account:boolean;prepare:()=>boolean;leave:(url:string)=>void}){
 const [status,setStatus]=useState<BillingStatus|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const attempt=useRef<string|null>(null);
 async function refresh(){if(!account)return;setBusy(true);setError('');try{const params=new URLSearchParams(location.search),session=params.get('session_id'),payment=params.get('payment');if(payment==='success'&&session){const r=await fetch('/api/billing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'confirm',sessionId:session})});const d=await r.json() as BillingStatus & {error?:string;confirmed?:boolean;url:string};if(!r.ok)throw Error(d.error);setStatus(d);setMessage(d.confirmed?'A vásárlást jóváírtuk. Az új projekthely felhasználható.':'A fizetés visszaigazolására várunk. Később frissítsd az állapotot.');if(d.confirmed){params.delete('payment');params.delete('session_id');history.replaceState(null,'',location.pathname+(params.size?'?'+params:''))}}else{const r=await fetch('/api/billing',{cache:'no-store'}),d=await r.json() as BillingStatus & {error?:string;confirmed?:boolean;url:string};if(!r.ok)throw Error(d.error);setStatus(d);if(payment==='cancelled')setMessage('A fizetést megszakítottad. A terved megmaradt, nem adtunk hozzá fizetett projekthelyet.')}}catch(e){setError(e instanceof Error?e.message:'A projekthelyek nem tölthetők be.')}finally{setBusy(false)}}
 useEffect(()=>{if(open)void refresh()},[open,account]);
 async function buy(){if(!status?.ready||busy)return;setBusy(true);setError('');try{attempt.current??=crypto.randomUUID();const r=await fetch('/api/billing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'checkout',requestId:attempt.current})});const d=await r.json() as BillingStatus & {error?:string;confirmed?:boolean;url:string};if(!r.ok){if(d.error?.includes("lejárt")||d.error?.includes("már jóváírtuk"))attempt.current=null;throw Error(d.error)}if(!prepare()){setBusy(false);return}leave(d.url)}catch(e){setError(e instanceof Error?e.message:'A fizetés nem indítható.');setBusy(false)}}
 return <Dialog open={open} onOpenChange={v=>{if(!busy)onOpenChange(v)}}><DialogContent className="billing-dialog"><DialogHeader><DialogTitle>Projekthelyek</DialogTitle><DialogDescription>Az első projekt fiókonként ingyenes. Minden további projekt egyszeri díja 3 490 Ft. Nincs havidíj.</DialogDescription></DialogHeader>{!account?<p>A további projektekhez jelentkezz be vagy regisztrálj. A meglévő terved megmarad.</p>:<><div className="billing-price"><strong>3 490 Ft</strong><span>egy további projekt · egyszeri fizetés</span></div>{status&&<p>Felhasználható: <b>{status.available} projekthely</b> ({status.free} ingyenes, {status.paid} vásárolt).</p>}{status?.mode==='test'&&<p className="billing-notice">Adminisztrátori tesztüzem. A tesztvásárlás csak tesztprojekthelyet ad, valódi terhelés nélkül.</p>}{status&&!status.ready&&<p>Az online fizetés még nincs bekapcsolva. A meglévő projektjeid továbbra is használhatók.</p>}{message&&<p role="status">{message}</p>}{error&&<p className="auth-error" role="alert">{error}</p>}<div className="project-actions"><button className="primary" disabled={busy||!status?.ready} onClick={()=>void buy()}>{busy?'Folyamatban…':status?.mode==='test'?'Tesztfizetés indítása':'Új projekthely – 3 490 Ft'}</button><button disabled={busy} onClick={()=>void refresh()}>Állapot frissítése</button></div><p className="auth-note">A bankkártyaadatokat a Stripe fizetési oldalán adod meg. A jóváírás után az Üres projekt vagy a Jelenlegi terv másolata gombbal használhatod fel a helyet.</p></>}</DialogContent></Dialog>;
}
