"use client";
import {useMemo,useState} from 'react';
import {ClipboardList,Download,Search,ArrowUpRight,BookOpen} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Plan} from '@/lib/plan';
import {materialList,materialsCsv,searchPlan,withAllowance,type SearchResult} from '@/lib/plan-tools';
const fmt=(n:number)=>n.toLocaleString('hu-HU',{maximumFractionDigits:2});
export function PlanTools({plan,onLocate}:{plan:Plan;onLocate:(result:SearchResult)=>void}){
 const[open,setOpen]=useState(false),[tab,setTab]=useState<'materials'|'search'>('materials'),[scope,setScope]=useState('all'),[allowance,setAllowance]=useState(10),[query,setQuery]=useState('');
 const rows=useMemo(()=>materialList(plan,scope),[plan,scope]),results=useMemo(()=>searchPlan(plan,query),[plan,query]);
 const meters=rows.filter(r=>r.unit==='m').reduce((s,r)=>s+r.quantity,0);
 function download(){const url=URL.createObjectURL(new Blob([materialsCsv(rows,allowance)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ShockCraft-anyagkimutatas.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <><button className="tools-button" aria-label="Keresés és anyagkimutatás" title="Keresés és anyagkimutatás" onClick={()=>setOpen(true)}><ClipboardList/><span>Eszközök</span></button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="plan-tools-dialog"><DialogHeader><DialogTitle>Tervsegéd</DialogTitle><DialogDescription>Keress a szobák, szerelvények, nyomvonalak és elosztókészülékek között, vagy készíts anyagkimutatást.</DialogDescription></DialogHeader>
 <div className="auth-tabs" role="group" aria-label="Tervsegéd nézet"><button className={tab==='materials'?'active':''} onClick={()=>setTab('materials')}><ClipboardList/> Anyagkimutatás</button><button className={tab==='search'?'active':''} onClick={()=>setTab('search')}><Search/> Keresés</button></div>
 {tab==='materials'?<><div className="report-controls"><label className="field"><span>Kimutatás területe</span><select aria-label="Kimutatás területe" value={scope} onChange={e=>setScope(e.target.value)}><option value="all">Teljes projekt és telek</option>{plan.buildings.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="field"><span>Kábelráhagyás (%)</span><input type="number" aria-label="Kábelráhagyás (%)" min={0} max={50} value={allowance} onChange={e=>setAllowance(Math.max(0,Math.min(50,Number(e.target.value)||0)))}/></label></div>
 <div className="report-totals"><div><span>Szerelvények</span><strong>{rows.filter(r=>r.category==='Szerelvény').reduce((s,r)=>s+r.quantity,0)} db</strong></div><div><span>Kábelhossz</span><strong>{fmt(meters)} m</strong></div><div><span>{allowance}% ráhagyással</span><strong>{fmt(meters*(1+allowance/100))} m</strong></div></div>
 <p className="report-note">A kábelhossz a rajzolt nyomvonalakból, a függőleges szakaszokkal együtt készül. Nyomvonalanként egy kábel szerepel. A kettős dugalj egy szerelvény; a telki jelöléshez kapcsolt elosztót egyszer számoljuk.</p>
 <div className="report-table"><table><thead><tr><th>Tétel / hely</th><th>Részletek</th><th>Terv szerint</th><th>Ráhagyással</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><b>{r.item}</b><small>{r.category} · {r.location}</small></td><td>{r.detail||'–'}</td><td>{fmt(r.quantity)} {r.unit}</td><td>{fmt(withAllowance(r,allowance))} {r.unit}</td></tr>)}</tbody></table>{!rows.length&&<p>Még nincs kimutatható szerelvény vagy nyomvonal.</p>}</div><button className="primary" onClick={download} disabled={!rows.length}><Download/> Anyagkimutatás letöltése (CSV)</button></>:<><label className="field"><span>Keresés az egész projektben</span><input autoFocus aria-label="Keresés a tervben" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pl. hálószoba, dugalj, D-01, világítás…"/></label><p className="report-note">{query.trim()?results.length+' találat. Válassz egy elemet a megnyitásához.':'A nevek, típusok, szintek és áramkörök között is kereshetsz.'}</p><div className="search-results">{results.slice(0,100).map(r=><button key={r.type+r.id} onClick={()=>{onLocate(r);setOpen(false)}}><span><b>{r.title}</b><small>{r.subtitle}</small></span><ArrowUpRight/></button>)}{query.trim()&&!results.length&&<p>Nincs találat. Próbálj rövidebb nevet vagy másik típust.</p>}{results.length>100&&<p>Az első 100 találat látható. Pontosítsd a keresést.</p>}</div></>}
 <a className="guide-link" href="/docs/ShockCraft-telepitesi-utmutato.pdf" target="_blank" rel="noreferrer"><BookOpen/> Telepítési útmutató (PDF)</a>
 </DialogContent></Dialog></>
}
