"use client";
import {useEffect,useMemo,useState} from 'react';
import {FileDown,Plus,RefreshCw,UserRound} from 'lucide-react';
import {toast} from 'sonner';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import {type Plan} from '@/lib/plan';
import {quoteSchema,type ProductDisplay,type Quote,type QuoteLine,type Travel} from '@/lib/quote-schema';
import {newQuote,addQuoteLine,quoteTotals,quoteIssues,quoteSource,lineTotal,money,amount,travelCost} from '@/lib/quote';
import {clientCustomerText,clientForProject,fillQuoteFromClient,type Client} from '@/lib/workbook';
import {fetchWorkbook} from '@/lib/workbook-client';
import {useCatalog} from './use-catalog';
import {ProductPicker,type PickTarget,type PickChoice} from './product-picker';
import {QuoteProducts} from './quote-products';
import {syncQuoteWithProducts,setProjectProduct,pinLineProduct,followProjectProduct,refIndex} from '@/lib/quote-products';
import {toSnapshot,productLabel,setAccountDefault} from '@/lib/catalog';

function NumberInput({label,value,max,decimals=2,nullable=false,onChange}:{label:string;value:number|null;max:number;decimals?:number;nullable?:boolean;onChange:(n:number|null)=>void}){
 const [draft,setDraft]=useState(value===null?'':String(value));useEffect(()=>setDraft(value===null?'':String(value)),[value]);
 function commit(){if(nullable&&draft.trim()===''){if(value!==null)onChange(null);return}const n=Number(draft);if(draft.trim()!==''&&Number.isFinite(n)&&n>=0&&n<=max){const rounded=Math.round(n*10**decimals)/10**decimals;if(rounded!==value)onChange(rounded);setDraft(String(rounded))}else{toast.error(`${label}: 0 és ${max} közötti értéket adj meg.`);setDraft(value===null?'':String(value))}}
 return <input aria-label={label} type="number" min={0} max={max} step={10**-decimals} placeholder={nullable?'Nincs ár':''} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur()}}/>;
}
export function QuoteEditor({plan,onChange,requireAccess,busy,userId,projectId,projectSaved}:{plan:Plan;onChange:(quote:Quote)=>void;requireAccess:()=>Promise<boolean>;busy:boolean;userId:string;projectId:string;projectSaved:boolean}){
 const empty=useMemo(()=>newQuote(),[]),q=plan.quote||empty,[pdfBusy,setPdfBusy]=useState(false),[confirm,setConfirm]=useState(false),[query,setQuery]=useState(''),[clientBusy,setClientBusy]=useState(false),[pendingClient,setPendingClient]=useState<Client|null>(null);
 const catalog=useCatalog(userId),[picking,setPicking]=useState<PickTarget|null>(null),refs=useMemo(()=>refIndex(plan),[plan]);
 const totals=quoteTotals(q),changed=!!q.sourceSignature&&q.sourceSignature!==quoteSource(plan),issues=quoteIssues(q),disabled=busy||pdfBusy||clientBusy||catalog.saving;
 function update(next:Quote){try{onChange(quoteSchema.parse(next))}catch(e){toast.error(e instanceof Error&&'issues' in e?'Ellenőrizd a dátumokat és a mezők megengedett hosszát.':e instanceof Error?e.message:'Az ajánlat nem módosítható.')}}
 function patch<K extends keyof Quote>(key:K,value:Quote[K]){update({...q,[key]:value})}
 function line(id:string,patch:Partial<QuoteLine>){update({...q,lines:q.lines.map(l=>l.id===id?{...l,...patch}:l)})}
 function refresh(){try{const r=syncQuoteWithProducts(plan,q);update(r.quote);setConfirm(false);toast.success('Az ajánlat mennyiségei frissítve a tervből.'+(r.priced>0?` ${r.priced} új tétel a projekt termékválasztásából árazva.`:''))}catch{toast.error('Legfeljebb 500 tételes ajánlat készíthető. Ellenőrizd a terv mennyiségeit is.')}}
 // Termékválasztás: a pillanatkép (és ára) a terv része lesz, ezért visszavonható; a fiók-alapértelmezés a katalógusba mentődik.
 function choose(t:PickTarget,c:PickChoice){try{
  if(t.kind==='slot'){if(c.type!=='product')return;const r=setProjectProduct(plan,q,t.ref,toSnapshot(c.product));update(r.quote);toast.success(`Termék beállítva: ${r.changed} tétel ára frissült.`);const own=catalog.catalog;if(c.remember&&own&&own.defaults.find(d=>d.ref===t.ref)?.productId!==c.product.id)void catalog.save(setAccountDefault(own,t.ref,c.product.id,t.label),'Fiók-alapértelmezés mentve.')}
  else if(c.type==='follow')update(followProjectProduct(plan,q,t.lineId));
  else if(c.type==='none')update(pinLineProduct(q,t.lineId,null));
  else update(pinLineProduct(q,t.lineId,toSnapshot(c.product)));
 }catch(e){toast.error(e instanceof Error?e.message:'A termék nem állítható be.')}finally{setPicking(null)}}
 // Pillanatkép az ügyféltörzsből; a terv része lesz, ezért visszavonható és a tervvel mentődik.
 function fill(c:Client){try{update(fillQuoteFromClient(q,c));toast.success('Az ügyfél adatai bekerültek az ajánlatba.')}catch{toast.error('Az ügyfél adatai nem vehetők át.')}finally{setPendingClient(null)}}
 async function takeClient(){setClientBusy(true);try{const c=clientForProject((await fetchWorkbook(userId)).workbook,projectId);if(!c){toast.info('Ehhez a projekthez még nincs ügyfél rendelve. A felső sáv Ügyfelek gombjával rendelheted hozzá.');return}if(q.customer.trim()&&q.customer.trim()!==clientCustomerText(c))setPendingClient(c);else fill(c)}catch(e){toast.error(e instanceof Error?e.message:'Az ügyféladatok nem tölthetők be.')}finally{setClientBusy(false)}}
 async function download(){setPdfBusy(true);try{if(!await requireAccess())return;const snapshot=quoteSchema.parse(q),problems=quoteIssues(snapshot);if(problems.length)throw Error(problems[0]);const r=await fetch('/fonts/NotoSans-Regular.ttf');if(!r.ok)throw Error('Nem tölthető be a PDF betűkészlete.');const bytes=new Uint8Array(await r.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const {createQuotePdf}=await import('@/lib/quote-pdf');const pdf=createQuotePdf(snapshot,plan.name,btoa(binary));pdf.save('Villanyrajz-arajanlat.pdf');toast.success('Az árajánlat PDF elkészült.')}catch(e){toast.error(e instanceof Error?e.message:'A PDF nem készíthető el.')}finally{setPdfBusy(false)}}
 const field=(label:string,key:'number'|'date'|'validUntil'|'supplier'|'customer'|'site'|'notes',max:number,multi=false)=><label className="field"><span>{label}</span>{multi?<textarea aria-label={label} value={q[key]} maxLength={max} rows={key==='notes'?4:3} onChange={e=>patch(key,e.target.value)}/>:<input aria-label={label} type={key==='date'||key==='validUntil'?'date':'text'} value={q[key]} maxLength={max} onChange={e=>patch(key,e.target.value)}/>}</label>;
 return <div className="quote-editor"><fieldset disabled={disabled}><div className="quote-intro"><div><h3>Árazás és árajánlat</h3><p>A megadott árak nettó egységárak, forintban. Az ajánlat a projekttel együtt mentődik.</p></div><button className="primary" onClick={()=>q.lines.length?setConfirm(true):refresh()}><RefreshCw/>{q.sourceSignature?'Mennyiségek frissítése':'Tételek átvétele a tervből'}</button></div>
 {changed&&<p className="warning-banner" role="status">A terv anyagkimutatása megváltozott. Az ajánlat a korábbi mennyiségeket őrzi; a frissítés külön gombbal indítható.</p>}
 <div className="quote-fields">{field('Ajánlat azonosítója','number',80)}{field('Kiállítás dátuma','date',10)}{field('Érvényes eddig','validUntil',10)}{field('Munkavégzés helye','site',500)}{field('Ajánlatadó adatai','supplier',1500,true)}{field('Ügyfél adatai','customer',1500,true)}</div>
 <div className="quote-client"><button type="button" disabled={!userId||!projectSaved} onClick={()=>void takeClient()}><UserRound/>{clientBusy?'Ügyféladatok betöltése…':'Ügyféladatok átvétele'}</button><small>{!userId?'Az ügyféltörzs fiókhoz kötött; vendég módban írd be kézzel az ügyfél adatait.':!projectSaved?'Mentsd a projektet, és rendelj hozzá ügyfelet a felső sáv Ügyfelek gombjával.':'A projekthez rendelt ügyfél adatai pillanatképként kerülnek az ajánlatba; a munkavégzés helye csak üres mező esetén töltődik ki.'}</small></div>
 <div className="quote-controls"><label className="field"><span>Kábelráhagyás (%)</span><NumberInput label="Ajánlati kábelráhagyás (%)" value={q.allowance} max={50} onChange={v=>patch('allowance',v!)}/></label><label className="field"><span>Kedvezmény (%)</span><NumberInput label="Ajánlati kedvezmény (%)" value={q.discount} max={100} onChange={v=>patch('discount',v!)}/></label><label className="field"><span>Áfa</span><select aria-label="Ajánlati áfa" value={q.vat} onChange={e=>patch('vat',e.target.value as Quote['vat'])}>{['AAM','0','5','18','27'].map(v=><option key={v} value={v}>{v==='AAM'?'Alanyi adómentes (AAM)':v+'%'}</option>)}</select></label><label className="field"><span>Termékadatok a PDF-ben</span><select aria-label="Termékadatok a PDF-ben" value={q.productDisplay??'brand'} onChange={e=>patch('productDisplay',e.target.value as ProductDisplay)}><option value="brand">Gyártó, termékcsalád, megnevezés</option><option value="sku">… és cikkszám</option><option value="none">Nem jelenik meg</option></select></label></div>
 <div className="quote-travel"><label className="field"><span>Útiköltség</span><select aria-label="Útiköltség típusa" value={q.travel?.mode||'none'} onChange={e=>{const m=e.target.value;if(m==='none'){patch('travel',undefined)}else{patch('travel',{mode:m as Travel['mode'],km:q.travel?.km??0,ratePerKm:q.travel?.ratePerKm??0,fixed:q.travel?.fixed??0})}}}><option value="none">Nincs útiköltség</option><option value="per_km">km alapon (táv × Ft/km)</option><option value="fixed">Fix összeg (Ft)</option></select></label>{q.travel?.mode==='per_km'&&<><label className="field"><span>Távolság (km)</span><NumberInput label="Távolság km" value={q.travel.km} max={9999} decimals={1} onChange={v=>patch('travel',{...q.travel!,km:v??0})}/></label><label className="field"><span>Díj (Ft/km)</span><NumberInput label="Ft per km" value={q.travel.ratePerKm} max={100000} onChange={v=>patch('travel',{...q.travel!,ratePerKm:v??0})}/></label><p className="report-note">Útiköltség: {amount(q.travel.km)} km × {money(q.travel.ratePerKm)} = <strong>{money(travelCost(q))}</strong></p></>}{q.travel?.mode==='fixed'&&<><label className="field"><span>Útiköltség összege (Ft)</span><NumberInput label="Fix útiköltség Ft" value={q.travel.fixed} max={10000000} onChange={v=>patch('travel',{...q.travel!,fixed:v??0})}/></label><p className="report-note">Fix útiköltség: <strong>{money(travelCost(q))}</strong></p></>}</div>
 <div className="quote-totals"><div><small>Anyag nettó</small><strong>{money(totals.material)}</strong></div><div><small>Munkadíj nettó</small><strong>{money(totals.labor)}</strong></div><div><small>Kedvezmény</small><strong>−{money(totals.discount)}</strong></div><div><small>Nettó összesen</small><strong>{money(totals.net)}</strong></div>{!!totals.travel&&<div><small>Útiköltség</small><strong>{money(totals.travel)}</strong></div>}<div><small>Áfa</small><strong>{money(totals.vat)}</strong></div><div><small>{totals.unpriced?'Részösszeg · hiányos árazás':'Fizetendő összesen'}</small><strong>{money(totals.total)}</strong></div></div>
 <p className="report-note">A ráhagyás csak a jelölt méteres tételekre vonatkozik, anyagra és munkadíjra egyaránt. A kedvezmény a tételek nettó összegéből kerül levonásra; az útiköltségre nem vonatkozik, de az áfa alapjába beleszámít. Hiányzó ár nem számít ingyenesnek: adj meg 0-t, ha az adott díj nem merül fel.</p>
 <QuoteProducts plan={plan} quote={q} userId={userId} catalog={catalog} onChange={update} onPick={setPicking}/>
 <label className="field"><span>Tételek keresése</span><input aria-label="Ajánlati tétel keresése" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Megnevezés vagy helyiség"/></label>
 <div className="quote-table"><table><thead><tr><th>Bevonva</th><th>Tétel / hely</th><th>Mennyiség</th><th>Egység</th><th>Anyag Ft/egység</th><th>Munkadíj Ft/egység</th><th>Nettó összeg</th></tr></thead><tbody>{q.lines.filter(l=>(l.name+' '+l.detail).toLocaleLowerCase('hu').includes(query.toLocaleLowerCase('hu'))).map((l)=>{const t=lineTotal(l,q),suffix=l.id;return <tr key={l.id} className={!l.included?'quote-excluded':''}><td><input type="checkbox" aria-label={'Bevonva: '+l.name} checked={l.included} onChange={e=>line(l.id,{included:e.target.checked})}/></td><td><input aria-label={'Tétel neve '+suffix} maxLength={240} value={l.name} onChange={e=>line(l.id,{name:e.target.value})}/><input aria-label={'Tétel részletei '+suffix} maxLength={500} value={l.detail} onChange={e=>line(l.id,{detail:e.target.value})}/><small>{l.sourceKey?'Tervből átvett':'Saját tétel'}</small>{(l.unit==='db'||l.unit==='m')&&<><button type="button" className="quote-product" disabled={!userId} onClick={()=>setPicking({kind:'line',lineId:l.id,label:l.name,unit:l.unit as 'db'|'m',fromPlan:!!l.sourceKey,pinned:!!l.productPinned,...(l.sourceKey&&refs.get(l.sourceKey)?{ref:refs.get(l.sourceKey)}:{})})}>{l.product?productLabel(l.product):'Termék választása…'}</button>{(l.product||l.productPinned)&&<small>{l.productPinned?(l.product?'Egyedi termék':'Egyedi: nincs termék'):'Projekt-alapértelmezés'}</small>}</>}{l.unit==='m'&&<label className="copy-option"><input type="checkbox" checked={l.allowance} onChange={e=>line(l.id,{allowance:e.target.checked})}/>Ráhagyás</label>}</td><td><NumberInput label={'Mennyiség '+suffix} value={l.quantity} max={10000} decimals={3} onChange={v=>line(l.id,{quantity:v!})}/>{l.unit==='m'&&l.allowance&&<small>Ráhagyással: {amount(t.quantity)} m</small>}</td><td><select aria-label={'Egység '+suffix} value={l.unit} onChange={e=>line(l.id,{unit:e.target.value as QuoteLine['unit']})}>{['db','m','óra','tétel'].map(u=><option key={u}>{u}</option>)}</select></td><td><NumberInput label={'Anyag egységár '+suffix} value={l.material} max={1000000} nullable onChange={v=>line(l.id,{material:v})}/>{l.product&&l.product.price!==null&&l.material!==l.product.price&&<small>Katalógusár: {money(l.product.price)}</small>}</td><td><NumberInput label={'Munkadíj egységár '+suffix} value={l.labor} max={1000000} nullable onChange={v=>line(l.id,{labor:v})}/></td><td><strong>{money(t.total)}</strong>{l.included&&(l.material===null||l.labor===null)&&<small>Hiányos ár</small>}</td></tr>})}</tbody></table>{!q.lines.length&&<p>Vedd át a terv tételeit, vagy adj hozzá saját tételt.</p>}</div>
 <button disabled={q.lines.length>=500} onClick={()=>patch('lines',[...q.lines,addQuoteLine()])}><Plus/> Saját tétel hozzáadása</button><p className="report-note">A kihagyott tételek megmaradnak, de nem szerepelnek az összegben és a PDF-ben. Az újra bevont tétel korábbi árai megőrződnek.</p>
 {field('Feltételek és megjegyzések','notes',5000,true)}
 {!!issues.length&&<div className="quote-issues"><b>A PDF-hez még szükséges:</b><ul>{issues.map(s=><li key={s}>{s}</li>)}</ul></div>}
 <button className="primary" disabled={!!issues.length} onClick={()=>void download()}><FileDown/>{pdfBusy?'PDF készítése…':'Árajánlat letöltése (PDF)'}</button><p className="report-note">Az ingyenes és a megvásárolt projekt ajánlata előfizetés nélkül is letölthető; az előfizetéses projekteké aktív előfizetéssel. Az ajánlat nem számla; elküldéséről te gondoskodsz.</p>
 </fieldset><Dialog open={confirm} onOpenChange={setConfirm}><DialogContent><DialogHeader><DialogTitle>Mennyiségek frissítése a tervből</DialogTitle><DialogDescription>A tervből átvett tételek neve, részletei, egysége és mennyisége frissül. A meglévő egységárak megmaradnak. A megszűnt tételek kimaradnak az összegből, a saját tételek változatlanok maradnak. A művelet a tervező Visszavonás gombjával visszavonható.</DialogDescription></DialogHeader><button className="primary" onClick={refresh}>Frissítés alkalmazása</button><button onClick={()=>setConfirm(false)}>Mégse</button></DialogContent></Dialog><Dialog open={!!pendingClient} onOpenChange={o=>{if(!o)setPendingClient(null)}}><DialogContent><DialogHeader><DialogTitle>Ügyféladatok felülírása</DialogTitle><DialogDescription>Az ajánlat „Ügyfél adatai” mezője lecserélődik a nyilvántartott adatokra. A munkavégzés helye csak üres mező esetén töltődik ki. A tervező Visszavonás gombjával visszavonható.</DialogDescription></DialogHeader><button className="primary" onClick={()=>{if(pendingClient)fill(pendingClient)}}>Felülírás</button><button onClick={()=>setPendingClient(null)}>Mégse</button></DialogContent></Dialog><ProductPicker target={picking} catalog={catalog} onChoose={choose} onClose={()=>setPicking(null)}/></div>;
}
