import {backgroundUrl} from './background';
import {type Plan,validatePlan} from './plan';
export async function uploadBackground(blob:Blob,userId:string){const r=await fetch('/api/backgrounds',{method:'POST',headers:{'Content-Type':'image/jpeg','X-ShockCraft-User':userId},body:blob});const d=await r.json() as {assetId?:string;userId?:string;error?:string};if(!r.ok||d.userId!==userId)throw Error(d.error||'A háttér nem menthető.');return d.assetId as string}
export function blobData(blob:Blob):Promise<string>{return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(Error('A kép nem olvasható.'));r.readAsDataURL(blob)})}
export async function backgroundData(ids:string[]){const files:Record<string,string>={};let size=0;for(const id of new Set(ids)){const r=await fetch(backgroundUrl(id));if(!r.ok)throw Error('Egy háttérkép nem érhető el. Próbáld újra, vagy távolítsd el a hiányzó hátteret.');const blob=await r.blob();size+=blob.size;if(size>28_000_000)throw Error('A háttérképek összesen legfeljebb 28 MB méretben exportálhatók.');files[id]=await blobData(blob)}return files}
export async function exportBackgroundPlan(plan:Plan){return {...plan,backgroundFiles:await backgroundData(plan.buildings.flatMap(b=>b.floors.flatMap(f=>f.background?[f.background.assetId]:[])))}}
export async function importBackgroundPlan(value:unknown,userId:string){const plan=validatePlan(value),files=(value as {backgroundFiles?:Record<string,unknown>}).backgroundFiles,ids=[...new Set(plan.buildings.flatMap(b=>b.floors.flatMap(f=>f.background?[f.background.assetId]:[])))],mapped=new Map<string,string>();
 // Validate all attachments before starting uploads. Old plans without backgrounds remain unchanged.
 const blobs=ids.map(id=>{const text=files&&Object.hasOwn(files,id)?files[id]:undefined;if(typeof text!=='string'||text.length>2_700_000||!/^data:image\/jpeg;base64,[A-Za-z0-9+/]+=*$/.test(text))throw Error('A tervhez tartozó háttérkép hiányzik vagy hibás. Exportáld újra az eredeti tervet.');const bytes=Uint8Array.from(atob(text.split(',')[1]),c=>c.charCodeAt(0));return new Blob([bytes],{type:'image/jpeg'})});
 for(let i=0;i<ids.length;i++)mapped.set(ids[i],await uploadBackground(blobs[i],userId));for(const b of plan.buildings)for(const f of b.floors)if(f.background)f.background.assetId=mapped.get(f.background.assetId)!;return plan;
}
