import {sqliteTable,text,integer,index,uniqueIndex,primaryKey} from "drizzle-orm/sqlite-core";
export const templateLibraries=sqliteTable('template_libraries',{userId:text('user_id').primaryKey(),data:text('data').notNull(),revision:integer('revision').notNull(),updatedAt:text('updated_at').notNull()});
export const planVersions=sqliteTable('plan_versions',{projectId:text('project_id').notNull(),revision:integer('revision').notNull(),data:text('data').notNull(),savedAt:text('saved_at').notNull()},t=>[primaryKey({columns:[t.projectId,t.revision]})]);
export const plans=sqliteTable("plans",{id:text("id").primaryKey(),data:text("data").notNull(),revision:integer("revision").notNull(),updatedAt:text("updated_at").notNull(),state:text('state').notNull().default('active'),stateChangedAt:text('state_changed_at')});
export const users=sqliteTable('users',{id:text('id').primaryKey(),email:text('email').notNull().unique(),name:text('name').notNull(),passwordHash:text('password_hash').notNull(),emailVerifiedAt:integer('email_verified_at'),authVersion:integer('auth_version').notNull().default(0),createdAt:integer('created_at').notNull()});
export const sessions=sqliteTable('sessions',{tokenHash:text('token_hash').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),expiresAt:integer('expires_at').notNull(),authVersion:integer('auth_version').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[index('sessions_user_idx').on(t.userId),index('sessions_expiry_idx').on(t.expiresAt)]);
export const authLimits=sqliteTable('auth_limits',{key:text('key').primaryKey(),attempts:integer('attempts').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('auth_limits_expiry_idx').on(t.expiresAt)]);
export const billingSettings=sqliteTable('billing_settings',{id:text('id').primaryKey(),data:text('data').notNull(),revision:integer('revision').notNull(),updatedAt:text('updated_at').notNull()});
export const billingGrants=sqliteTable('billing_grants',{id:text('id').primaryKey(),userId:text('user_id').notNull(),projectId:text('project_id'),mode:text('mode').notNull(),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('billing_grants_project_unique').on(t.userId,t.projectId),index('billing_grants_user_idx').on(t.userId)]);
export const billingOrders=sqliteTable('billing_orders',{kind:text('kind').notNull().default('project'),id:text('id').primaryKey(),userId:text('user_id').notNull(),amount:integer('amount').notNull(),currency:text('currency').notNull(),mode:text('mode').notNull(),status:text('status').notNull(),sessionId:text('session_id'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[uniqueIndex('billing_orders_session_unique').on(t.sessionId),index('billing_orders_user_idx').on(t.userId)]);


export const mailSettings=sqliteTable('mail_settings',{id:text('id').primaryKey(),data:text('data').notNull(),revision:integer('revision').notNull(),updatedAt:text('updated_at').notNull()});
export const accountTokens=sqliteTable('account_tokens',{tokenHash:text('token_hash').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),email:text('email').notNull(),purpose:text('purpose').notNull(),authVersion:integer('auth_version').notNull(),expiresAt:integer('expires_at').notNull(),createdAt:integer('created_at').notNull()},t=>[index('account_tokens_user_idx').on(t.userId),index('account_tokens_expiry_idx').on(t.expiresAt)]);

export const billingSubscriptions=sqliteTable('billing_subscriptions',{id:text('id').primaryKey(),userId:text('user_id').notNull(),mode:text('mode').notNull(),orderId:text('order_id').notNull().unique(),customerId:text('customer_id').notNull(),status:text('status').notNull(),paidUntil:integer('paid_until').notNull().default(0),cancelAtPeriodEnd:integer('cancel_at_period_end').notNull().default(0),revision:integer('revision').notNull().default(0),updatedAt:integer('updated_at').notNull()},t=>[index('billing_subscriptions_user_mode_idx').on(t.userId,t.mode)]);
export const subscriptionCheckouts=sqliteTable('subscription_checkouts',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),expiresAt:integer('expires_at').notNull()});

export const invoiceSettings=sqliteTable('invoice_settings',{id:text('id').primaryKey(),data:text('data').notNull(),revision:integer('revision').notNull(),updatedAt:text('updated_at').notNull()});
export const billingProfiles=sqliteTable('billing_profiles',{userId:text('user_id').primaryKey(),data:text('data').notNull(),updatedAt:integer('updated_at').notNull()});
export const orderBilling=sqliteTable('order_billing',{orderId:text('order_id').primaryKey(),data:text('data').notNull()});
export const invoiceJobs=sqliteTable('invoice_jobs',{id:text('id').primaryKey(),userId:text('user_id').notNull(),mode:text('mode').notNull(),payload:text('payload').notNull(),status:text('status').notNull(),number:text('number'),error:text('error'),attempts:integer('attempts').notNull().default(0),lockUntil:integer('lock_until').notNull().default(0),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('invoice_jobs_user_idx').on(t.userId),index('invoice_jobs_status_idx').on(t.status)]);
export const workbooks=sqliteTable('workbooks',{userId:text('user_id').primaryKey().references(()=>users.id,{onDelete:'cascade'}),data:text('data').notNull(),revision:integer('revision').notNull(),updatedAt:text('updated_at').notNull()});
export const planShares=sqliteTable('plan_shares',{id:text('id').primaryKey(),tokenHash:text('token_hash').notNull(),ownerId:text('owner_id').notNull().references(()=>users.id,{onDelete:'cascade'}),projectId:text('project_id').notNull(),projectKey:text('project_key').notNull(),label:text('label').notNull().default(''),allowPdf:integer('allow_pdf').notNull().default(0),authVersion:integer('auth_version').notNull(),createdAt:integer('created_at').notNull(),expiresAt:integer('expires_at').notNull(),lastViewedAt:integer('last_viewed_at')},t=>[uniqueIndex('plan_shares_token_unique').on(t.tokenHash),index('plan_shares_owner_project_idx').on(t.ownerId,t.projectKey),index('plan_shares_expiry_idx').on(t.expiresAt)]);
