import {z} from 'zod';
import {withDatabase} from '@/db/database';
import {accountFromHeaders,privateHeaders,sameOrigin} from '@/lib/auth';
import {billingEnv,insertIgnore,isAdmin} from '@/lib/billing';
import {invoiceConfig,processInvoice} from '@/lib/invoicing';
import {seal} from '@/lib/secrets';
export async function GET(req:Request){try{return await withDatabase(async db=>{if(!isAdmin(await accountFromHeaders(db,req.headers)))return Response.json({error:'Adminisztrátori jogosultság szükséges.'},{status:403,headers:privateHeaders});const {config,revision}=await invoiceConfig(db);return Response.json({...config,testKey:!!config.testKey,liveKey:!!config.liveKey,revision,encryptionReady:!!billingEnv().BILLING_ENCRYPTION_KEY,jobs:await db.all('SELECT id,mode,status,number,error,attempts,created_at FROM invoice_jobs ORDER BY created_at DESC LIMIT 100')},{headers:privateHeaders})})}catch{return Response.json({error:'A számlázási beállítások nem tölthetők be.'},{status:503,headers:privateHeaders})}}
export async function POST(req:Request){if(!sameOrigin(req))return Response.json({error:'Érvénytelen kérés.'},{status:403,headers:privateHeaders});const raw=await req.text();if(raw.length>4096)return Response.json({error:'Túl nagy kérés.'},{status:413,headers:privateHeaders});try{return await withDatabase(async db=>{if(!isAdmin(await accountFromHeaders(db,req.headers)))return Response.json({error:'Adminisztrátori jogosultság szükséges.'},{status:403,headers:privateHeaders});const body=JSON.parse(raw);if(body.action==='retry'){const id=z.string().max(180).parse(body.id);if(!await processInvoice(db,id))throw Error('A megfelelő Agent-kulcs és az automatikus számlázás bekapcsolása szükséges.');return Response.json({ok:true},{headers:privateHeaders})}
 const data=z.object({enabled:z.boolean(),testKey:z.string().trim().max(500),liveKey:z.string().trim().max(500),prefix:z.string().trim().max(20).regex(/^[\p{L}\p{N}_-]*$/u),replyTo:z.string().trim().email().max(254),duplicateProtection:z.boolean(),revision:z.number().int().nonnegative()}).parse(body);const {config,revision}=await invoiceConfig(db);if(revision!==data.revision)return Response.json({error:'Másik ablak módosította. Frissítsd az adatokat.'},{status:409,headers:privateHeaders});const next={enabled:data.enabled,testKey:data.testKey||config.testKey,liveKey:data.liveKey||config.liveKey,prefix:data.prefix,replyTo:data.replyTo,duplicateProtection:data.duplicateProtection,vat:'AAM' as const};if(next.enabled&&(!next.duplicateProtection||!next.testKey&&!next.liveKey))throw Error('Agent-kulcs és a rendelésszám-ismétlődés tiltása szükséges.');const encrypted=await seal(next),now=new Date().toISOString();const changed=revision===0?await db.run(insertIgnore(db,'INSERT INTO invoice_settings (id,data,revision,updated_at) VALUES (?,?,?,?)'),['szamlazz',encrypted,1,now]):await db.run('UPDATE invoice_settings SET data = ?, revision = revision + 1, updated_at = ? WHERE id = ? AND revision = ?',[encrypted,now,'szamlazz',revision]);return Response.json(changed?{ok:true}:{error:'A beállítás megváltozott. Frissítsd az oldalt.'},{status:changed?200:409,headers:privateHeaders})})}catch(e){return Response.json({error:e instanceof Error&&!['ZodError','SyntaxError'].includes(e.name)?e.message:'Érvénytelen számlázási beállítás.'},{status:400,headers:privateHeaders})}}
